objects/Action_Item__c.object
<CustomObject>
    <fields>
        <fullName>Change_Control__c</fullName>
        <label>Change Control</label>
        <referenceTo>CMPL123QMS__Change_Control__c</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Action_Item__c</fullName>
        <label>Action Item</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMPL123_WF_Action__c</fullName>
        <label>Workflow Action</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMPL123_WF_Status__c</fullName>
        <label>Workflow Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Predefined_Implementation_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Predefined Implementation Plan</label>
        <referenceTo>Predefined_Implementation_Plan__c</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Action Item</label>
    <nameField>
        <displayFormat>AI-{0000}</displayFormat>
        <label>Action Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CMPL123__Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMPL123CME__Complaint__c.object
<CustomObject>
    <fields>
        <fullName>CMPL123CME__Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Complaints_Assigned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Impact__c</fullName>
        <description>Impact</description>
        <label>Impact</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Initiator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Initiator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Complaints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Short_Description__c</fullName>
        <description>Short Description</description>
        <label>Short Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Complaints_Supervisor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMPL123Task_Key_Value__c</fullName>
        <label>Task Field Update Key Value</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Ticket No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMPL123QMS__Change_Control__c.object
<CustomObject>
    <label>Change Control</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Change Control Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Control</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Extension_Request_Change_Control__c.object
<CustomObject>
    <fields>
        <fullName>CMPL123_WF_Action__c</fullName>
        <label>Workflow Action</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMPL123_WF_Status__c</fullName>
        <label>Workflow Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Control__c</fullName>
        <label>Change Control</label>
        <referenceTo>CMPL123QMS__Change_Control__c</referenceTo>
        <relationshipLabel>Extension Requests Change Control</relationshipLabel>
        <relationshipName>Extension_Requests_Change_Control</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMPL123Task_Key_Value__c</fullName>
        <label>Task Field Update Key Value</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <label>Extension Request Change Control</label>
    <nameField>
        <displayFormat>ER-CC-{00000}</displayFormat>
        <label>ER-CC No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Extension Requests Change Control</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Impact_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Change_Control__c</fullName>
        <label>Change Control</label>
        <referenceTo>CMPL123QMS__Change_Control__c</referenceTo>
        <relationshipLabel>Impact Assessments</relationshipLabel>
        <relationshipName>Impact_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CMPL123_WF_Action__c</fullName>
        <label>Workflow Action</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMPL123_WF_Status__c</fullName>
        <label>Workflow Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>impact_Assessment__c</fullName>
        <label>Impact Assessment</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMPL123Task_Key_Value__c</fullName>
        <label>Task Field Update Key Value</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <label>Impact Assessment</label>
    <nameField>
        <displayFormat>CC-IA-{0000}</displayFormat>
        <label>Impact Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Impact Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Predefined_Action_Item__c.object
<CustomObject>
    <fields>
        <fullName>Predefined_Implementation_Plan__c</fullName>
        <label>Predefined Implementation Plan</label>
        <referenceTo>Predefined_Implementation_Plan__c</referenceTo>
        <relationshipLabel>Predefined Action Items</relationshipLabel>
        <relationshipName>Predefined_Action_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Predefined Action Item</label>
    <nameField>
        <displayFormat>Pre-AI-{0000}</displayFormat>
        <label>Predefined Action Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Predefined Action Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Predefined_Implementation_Plan__c.object
<CustomObject>
    <label>Predefined Implementation Plan</label>
    <nameField>
        <label>Predefined Implementation Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Predefined Implementation Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>TWD_Role__c</fullName>
        <label>TWD Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Change Coordinator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestSetup.cls
/**
 * @File Name          : TestSetup.cls
 * @Description        : 
 * @Author             : Jon Astemborski
 * @Group              : 
 * @Last Modified By   : Jon Astemborski
 * @Last Modified On   : 6/9/2020, 12:12:33 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    1/16/2020   Jon Astemborski     Initial Version
**/
@IsTest
public class TestSetup{
    private static final String WF_ACTION_API_NAME = 'CMPL123_WF_Action__c';
    private static final String WF_STATUS_API_NAME = 'CMPL123_WF_Status__c';
    private static final String ID_NAME = 'Id';

     public static CMPL123__Product__c createProduct(Boolean withId, String name, String code) {
        CMPL123__Product__c product = new CMPL123__Product__c(
                Name = name,
                CMPL123__Serial_No__c = '66666',
                CMPL123__Product_Code__c = code,
                CMPL123__Type__c = 'Drug',
                CMPL123__Active__c = true
        );
        if (withId) {
            insert product;
        }
        return product;
    }

    public static Impact_Assessment__c createIA(Boolean withId, Id ccId){
        Impact_Assessment__c ia = new Impact_Assessment__c();
        ia.change_control__c = ccId;
        ia.CMPL123_WF_Status__c = 'Open';
        ia.CMPL123Task_Key_Value__c = '';
        if (withId) {
            insert ia;
        }
        return ia;
    }

    public static Extension_Request_Change_Control__c createExtCC(Boolean withId, Id ccId){
        Extension_Request_Change_Control__c extReq = new Extension_Request_Change_Control__c();
        extReq.Change_Control__c = ccId;
        if (withId) {
            insert extReq;
        }
        return extReq;
    }

    public static Predefined_Action_Item__c createPredefinedAI(Boolean withId, Id planId){
        Predefined_Action_Item__c preAi = new Predefined_Action_Item__c();
        preAi.Predefined_Implementation_Plan__c = planId;
        if (withId) {
            insert preAi;
        }
        return preAi;
    }

    public static Predefined_Implementation_Plan__c createdPredefinedImplementationPlan(Boolean withId){
        Predefined_Implementation_Plan__c plan = new Predefined_Implementation_Plan__c();
        if (withId) {
            insert plan;
        }
        return plan;
    }

    public static Action_Item__c createAIWithCC(Boolean withId, Id ccId) {
        Action_Item__c ai = new Action_Item__c();
        ai.change_control__c = ccId;
        ai.CMPL123_WF_Status__c = 'Open';
        ai.Action_Item__c = 'test';
        ai.CMPL123Task_Key_Value__c = '';
        if (withId) {
            insert ai;
        }
        return ai;
    }

    public static CMPL123CME__Complaint__c  createComplaint(Boolean withId) {
        CMPL123CME__Complaint__c complaintObj = new CMPL123CME__Complaint__c();
        complaintObj.CMPL123CME__Assigned_To__c = createUser(true).Id;
        complaintObj.CMPL123CME__Short_Description__c ='UnitTest';
        complaintObj.CMPL123CME__Initiator__c = createUser(true).Id;
        complaintObj.CMPL123CME__Supervisor__c = createUser(true).Id;
        complaintObj.CMPL123CME__Impact__c = 'Low';
        if (withId) {
            insert complaintObj;
        }
        return complaintObj;
    }

    public static CMPL123QMS__Change_Control__c  createCC(Boolean withId, Id recordTypeId) {
       CMPL123QMS__Change_Control__c cc = new CMPL123QMS__Change_Control__c();
        cc.Title__c = 'Test';
        cc.Change_Owner__c = createUser(true).id;
        cc.Origination__c = 'Corporate';
        cc.recordTypeId = recordTypeId;
        if (withId) {
            insert cc;
        }
        return cc;
    }

    public static Account  createAccount(Boolean withId) {
        Account acc = new Account();
        acc.name = 'test';
        if (withId) {
            insert acc;
        }
        return acc;
    }

    public static User createUser(Boolean withId){
        Profile stdProfile = [SELECT Id, Name FROM Profile WHERE Name ='System Administrator'];
        Blob blobKey = crypto.generateAesKey(128);
        String key = EncodingUtil.convertToHex(blobKey);
        User standard = new User(Alias = 'johnd',
                                Email = 'johndoe@test.com',
                                Emailencodingkey = 'UTF-8',
                                Firstname = 'John',
                                Lastname = 'Doe',
                                Languagelocalekey = 'en_US',
                                Localesidkey = 'en_US',
                                Profileid = stdProfile.Id,
                                Timezonesidkey ='America/Los_Angeles',
                                TWD_Role__c = 'Change Coordinator',
                                Username = 'test' + key.substring(0,15) + '@' + key.substring(16,22)+'.com'
                                );
        if(withId){
            insert standard;
        }
        return standard;
    }
}