objects/Action_Item__c.object
<CustomObject>
    <fields>
        <fullName>Change_Control__c</fullName>
        <label>Change Control</label>
        <referenceTo>CMPL123QMS__Change_Control__c</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Action_Item__c</fullName>
        <label>Action Item</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMPL123_WF_Status__c</fullName>
        <label>Workflow Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Action Item</label>
    <nameField>
        <displayFormat>AI-{0000}</displayFormat>
        <label>Action Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Batch_Child_Workflow_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Child_Object_API_Name__c</fullName>
        <label>Child Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Child_Workflow_Status__c</fullName>
        <label>Child Workflow Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Field_API_Name__c</fullName>
        <inlineHelpText>This is the parent field that resides on the child object</inlineHelpText>
        <label>Child Lookup To Parent Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Object_API_Name__c</fullName>
        <label>Parent Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Workflow_Status__c</fullName>
        <label>Parent Workflow Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X123_Task_Key_Value__c</fullName>
        <label>123 Task Key Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Batch Child Workflow Mapping</label>
    <pluralLabel>Batch Child Workflow Mapping</pluralLabel>
</CustomObject>

objects/CMPL123QMS__Change_Control__c.object
<CustomObject>
    <label>Change Control</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Change Control Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Control</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchChildWorkflowHandlerTest.cls
@IsTest
public class BatchChildWorkflowHandlerTest {
    @IsTest static void createQuery_validQuery(){
        Batch_Child_Workflow_Mapping__mdt batchMapping = new Batch_Child_Workflow_Mapping__mdt(X123_Task_Key_Value__c='CancelOpenAI', Parent_Field_API_Name__c='Change_Control__c',
                Child_Workflow_Status__c='Open',Parent_Object_API_Name__c='CMPL123QMS__Change_Control__c', Parent_Workflow_Status__c='Closed - Canceled',
                Child_Object_API_Name__c='Action_Item__c', MasterLabel='Cancel All Open CC AIs - Test', DeveloperName='Cancel_All_Open_CC_AIs_Test');

        BatchChildWorkflowHandler handler = new BatchChildWorkflowHandler();
        Id ccRecType = Schema.SObjectType.CMPL123QMS__Change_Control__c.getRecordTypeInfosByName().get('CC Custom').getRecordTypeId();
        CMPL123QMS__Change_Control__c cc = TestSetup.createCC(true, ccRecType);
        handler.parentRecordId = cc.id;

        String query = handler.createQuery(batchMapping);
        String expectedQuery = 'SELECT ID, CMPL123Task_Key_Value__c, CMPL123_WF_Status__c,' + batchMapping.Parent_Field_API_Name__c + 
        ' FROM ' + batchMapping.Child_Object_API_Name__c + 
        ' WHERE CMPL123_WF_Status__c =\'' +  batchMapping.Child_Workflow_Status__c + '\' AND ' +
         batchMapping.Parent_Field_API_Name__c + ' = \'' + cc.id + '\'';
        System.assertEquals(expectedQuery, query);
    }
}