objects/Batch_Child_Workflow_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Child_Object_API_Name__c</fullName>
        <label>Child Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Child_Workflow_Status__c</fullName>
        <label>Child Workflow Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Field_API_Name__c</fullName>
        <inlineHelpText>This is the parent field that resides on the child object</inlineHelpText>
        <label>Child Lookup To Parent Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Object_API_Name__c</fullName>
        <label>Parent Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Workflow_Status__c</fullName>
        <label>Parent Workflow Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X123_Task_Key_Value__c</fullName>
        <label>123 Task Key Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Batch Child Workflow Mapping</label>
    <pluralLabel>Batch Child Workflow Mapping</pluralLabel>
</CustomObject>

objects/Workflow_Batch_Size__mdt.object
<CustomObject>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <label>Batch Size</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Workflow Batch Size</label>
    <pluralLabel>Workflow Batch Size</pluralLabel>
</CustomObject>

classes/ProcessBatchChildWorkflow.cls
public without Sharing class ProcessBatchChildWorkflow {
    public ProcessBatchChildWorkflow() {

    }

    public static void processBatchChildWorkflows(String parentApiName, Map<Id,SObject> objectMap){
        System.debug('process batch ');
        Set<Id> keySet = objectMap.keySet();
        Id objectId;
        SObject obj;
        for ( Id objID : keySet) {
            obj = objectMap.get(objId);
        }
        Integer childBatchSize = 10;
        List<Workflow_Batch_Size__mdt> childBatchSizeList = [SELECT Batch_Size__c FROM Workflow_Batch_Size__mdt where DeveloperName =: parentApiName];
        if (!childBatchSizeList.isEmpty()){
            childBatchSize = childBatchSizeList.get(0).Batch_Size__c.intValue();
        }
        String parentWorkflowStatus = obj.get('CMPL123_WF_Status__c').toString();
        List<Batch_Child_Workflow_Mapping__mdt> workflowMappingList = [SELECT X123_Task_Key_Value__c, Parent_Field_API_Name__c, Child_Workflow_Status__c,
                                Parent_Object_API_Name__c, Parent_Workflow_Status__c, Child_Object_API_Name__c from Batch_Child_Workflow_Mapping__mdt
                                where Parent_Object_API_Name__c =: parentApiName and Parent_Workflow_Status__c =: parentWorkflowStatus];
        System.debug('parentApiName : ' + parentApiName);
        System.debug('parentWorkflowStatus : ' + parentWorkflowStatus);
        
        System.debug('workflow mapping: ' + workflowMappingList);
        if ( !workflowMappingList.isEmpty()) {
            Id recordId = (Id)obj.get('Id');
            BatchChildWorkflowHandler wfHandler = new BatchChildWorkflowHandler(workflowMappingList, childBatchSize, recordId, 0);
            Database.executeBatch(wfHandler, childBatchSize);
        }
    }
}