objects/CAPA_Effectiveness_Check__c.object
<CustomObject>
    <fields>
        <fullName>CAPA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CAPA</label>
        <referenceTo>CMPL123QMS__CAPA__c</referenceTo>
        <relationshipLabel>CAPA Effectiveness Checks</relationshipLabel>
        <relationshipName>CAPA_Effectiveness_Checks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMPL123_WF_Status__c</fullName>
        <label>Workflow Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CAPA Effectiveness Check</label>
    <nameField>
        <displayFormat>CAPA-EC-{00000}</displayFormat>
        <label>CAPA Effectiveness Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CAPA Effectiveness Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Change_Control_Plan__c.object
<CustomObject>
    <fields>
        <fullName>CMPL123_WF_Status__c</fullName>
        <label>Workflow Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Control_Plan_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Change Control Plan Approved?</label>
        <type>Checkbox</type>
    </fields>
    <label>Change Control Plan</label>
    <nameField>
        <label>Change Control Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Change Control Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMPL123__Device__c.object
<CustomObject>
    <description>Device</description>
    <label>Device</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMPL123QMS__CAPA__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <description>Action Plan</description>
        <label>Action Plan Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actual_Risk_Rating__c</fullName>
        <label>Actual Risk Rating</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Risk__c</fullName>
        <label>Business Risk</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CAPA_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CAPA Owner</description>
        <label>CAPA Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>CAPAs (CAPA Owner)</relationshipLabel>
        <relationshipName>CAPAsOwner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMPL123QMS__CAPA_Type__c</fullName>
        <label>CAPA Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corrective Action</fullName>
                </value>
                <value>
                    <fullName>Preventive Action</fullName>
                </value>
                <value>
                    <fullName>Correction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CMPL123_WF_Status__c</fullName>
        <label>Workflow Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Compliance_Risk__c</fullName>
        <label>Compliance Risk</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Initiated__c</fullName>
        <description>Date Initiated</description>
        <label>Date Initiated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Device_Problem__c</fullName>
        <label>Device Problem?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Device__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Device</label>
        <referenceTo>CMPL123__Device__c</referenceTo>
        <relationshipLabel>CAPAs</relationshipLabel>
        <relationshipName>CAPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Health_Risk__c</fullName>
        <label>Health Risk?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Investigation_Required__c</fullName>
        <description>Investigation Required?</description>
        <label>Investigation Required?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Probability_Measure__c</fullName>
        <label>Probability Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Risk_Category__c</fullName>
        <label>Risk Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Severity_Measure__c</fullName>
        <label>Severity Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>Short Description</description>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CAPA</label>
    <nameField>
        <displayFormat>CAPA-{00000}</displayFormat>
        <label>CAPA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CAPAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CAPAEffectivenessHandler_Test.cls
@IsTest public class CAPAEffectivenessHandler_Test {
     @IsTest public static void testCAPAEffectivenessHandlerNegative () {
       
         // User initialization
         Profile p = [select id from profile where name='Standard User'];
         
         User testUserCAPA1 = new User(alias = 'utest', email='utest@email.com',
                           emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                           localesidkey='en_US', profileid = p.Id, country='United States',
                           timezonesidkey='America/Los_Angeles', username='utestCAPA1@email.com');
         insert testUserCAPA1;
       
         //Devices
         CMPL123__Device__c device = new CMPL123__Device__c();
         device.Name = '123Test';
         try{
         insert device;
         }
         catch(Exception ex)
         {
             system.debug(ex);
         }
         
         //CAPA Object
         CMPL123QMS__CAPA__c capaObj = new CMPL123QMS__CAPA__c();
         capaObj.CMPL123QMS__CAPA_Type__c = 'Corrective Action';
         capaObj.Description__c = 'UTest';
         capaObj.Short_Description__c = 'UTest';
         capaObj.Date_Initiated__c = Date.today();
         capaObj.Device__c = device.id;
         capaObj.Device_Problem__c = 'Yes';
         capaObj.Health_Risk__c ='Yes';
         capaObj.Business_Risk__c ='High';
         capaObj.Probability_Measure__c = 'Low';
         capaObj.Actual_Risk_Rating__c = 'Low';
         capaObj.Compliance_Risk__c = 'High';
         capaObj.Severity_Measure__c ='High';
         capaObj.Risk_Category__c = 'Low';
         capaObj.Investigation_Required__c = 'Yes';
         capaObj.CAPA_Owner__c = testUserCAPA1.id;
         capaObj.Action_Plan__c ='To Test!';
         //capaObj.CMPL123_WF_Status__c = 'Closed - CAPA';
         insert capaObj;
         
         // CAPA_Effectiveness_Check__c Object
         CAPA_Effectiveness_Check__c capaEffObj = new CAPA_Effectiveness_Check__c();
         capaEffObj.CAPA__c = capaObj.id;
         
         insert capaEffObj;
         update capaEffObj;
         delete capaEffObj;
         undelete capaEffObj;
             
         
        }
        
        @IsTest(SeeAllData=true)  public static void testCAPAEffectivenessHandlerPositive () {
       
        // User initialization
        Profile p = [select id from profile where name='Standard User'];

        User testUserCAPA2 = new User(alias = 'utest', email='utest@email.com',
            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
            localesidkey='en_US', profileid = p.Id, country='United States',
            timezonesidkey='America/Los_Angeles', username='utestCAPA2@email.com');
        insert testUserCAPA2;
         //Devices
        
        CMPL123__Device__c device = new CMPL123__Device__c();
        device.Name = 'ABCDTEST2';
        insert device;
         
            //CAPA Object
            CMPL123QMS__CAPA__c capaObj = new CMPL123QMS__CAPA__c();
            capaObj.CMPL123QMS__CAPA_Type__c = 'Corrective Action';
            capaObj.Description__c = 'UTest';
            capaObj.Short_Description__c = 'UTest';
            capaObj.Date_Initiated__c = Date.today();
            capaObj.Device__c = device.id;
            capaObj.Device_Problem__c = 'Yes';
            capaObj.Health_Risk__c ='Yes';
            capaObj.Business_Risk__c ='High';
            capaObj.Probability_Measure__c = 'Low';
            capaObj.Actual_Risk_Rating__c = 'Low';
            capaObj.Compliance_Risk__c = 'High';
            capaObj.Severity_Measure__c ='High';
            capaObj.Risk_Category__c = 'Low';
            capaObj.Investigation_Required__c = 'Yes';
            capaObj.CAPA_Owner__c = testUserCAPA2.id;
            capaObj.Action_Plan__c ='To Test!';
            try{
            insert capaObj;
            }
            catch(Exception ex)
            {
                system.debug(ex);
            }
            // CAPA_Effectiveness_Check__c Object
            CAPA_Effectiveness_Check__c capaEffObj = new CAPA_Effectiveness_Check__c();
            capaEffObj.CAPA__c = capaObj.id;
            insert capaEffObj;
        
            //create a task for the user
            //Task newTask = new Task(Subject='Complete Survey for Transaction');
            
            Change_Control_Plan__c changeCntrlRec = new Change_Control_Plan__c(Change_Control_Plan_Approved__c = true);
            insert changeCntrlRec;
            
            List<Task> taskList = new List<Task>();
            Task newTask = new Task(Subject = 'Call',
                                    Description = 'Survey Transaction',
                                    Priority = 'Normal', 
                                    Status = 'In Progress', 
                                    IsReminderSet = true, 
                                    whatId = changeCntrlRec.Id,
                                    ReminderDateTime = System.now()+1); 
            try{
                insert newTask;
            }
            catch(Exception ex){
                            system.debug('In the + method ' + ex);
            }
            
            taskList.add(newTask);
            TaskPreventionHandler.preventTaskAddAndDelete(taskList,'insert');
            TaskPreventionHandler.preventTaskAddAndDelete(taskList,'delete');
        }

}