objects/CAPA_Plan__c.object
<CustomObject>
    <fields>
        <fullName>CAPA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CAPA</label>
        <referenceTo>CMPL123QMS__CAPA__c</referenceTo>
        <relationshipLabel>CAPA Plans</relationshipLabel>
        <relationshipName>CAPA_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CAPA Plan</label>
    <nameField>
        <label>CAPA Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CAPA Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMPL123__Device__c.object
<CustomObject>
    <description>Device</description>
    <label>Device</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMPL123QMS__CAPA__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <description>Action Plan</description>
        <label>Action Plan Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actual_Risk_Rating__c</fullName>
        <label>Actual Risk Rating</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Risk__c</fullName>
        <label>Business Risk</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CAPA_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CAPA Owner</description>
        <label>CAPA Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>CAPAs (CAPA Owner)</relationshipLabel>
        <relationshipName>CAPAsOwner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMPL123QMS__CAPA_Type__c</fullName>
        <label>CAPA Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corrective Action</fullName>
                </value>
                <value>
                    <fullName>Preventive Action</fullName>
                </value>
                <value>
                    <fullName>Correction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Compliance_Risk__c</fullName>
        <label>Compliance Risk</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Initiated__c</fullName>
        <description>Date Initiated</description>
        <label>Date Initiated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Device_Problem__c</fullName>
        <label>Device Problem?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Device__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Device</label>
        <referenceTo>CMPL123__Device__c</referenceTo>
        <relationshipLabel>CAPAs</relationshipLabel>
        <relationshipName>CAPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Health_Risk__c</fullName>
        <label>Health Risk?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Investigation_Required__c</fullName>
        <description>Investigation Required?</description>
        <label>Investigation Required?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Probability_Measure__c</fullName>
        <label>Probability Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Risk_Category__c</fullName>
        <label>Risk Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Severity_Measure__c</fullName>
        <label>Severity Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>Short Description</description>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CAPA</label>
    <nameField>
        <displayFormat>CAPA-{00000}</displayFormat>
        <label>CAPA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CAPAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CAPAPlanHandler_Test.cls
/*
File Name: CAPAPlanHandler_Test
Author: Sparta Systems
Description: public method, which is referenced in the CAPA plan audit trigger.
Requirement: JIRA 819 , User should not be able to Send Action Plan for Approval without any Tasks
*/

@IsTest public class CAPAPlanHandler_Test {
    @IsTest public static void testCAPAPlanHandler() {
      // User initialization
        Profile p = [select id from profile where name='Standard User'];

        User u = new User(alias = 'utest', email='utest@email.com',
            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
            localesidkey='en_US', profileid = p.Id, country='United States',
            timezonesidkey='America/Los_Angeles', username='utest123@email.com');
        insert u;
        
        //Devices
        
        CMPL123__Device__c device = new CMPL123__Device__c();
        device.Name = '12345';
        insert device;
        
        //CAPA Object
        CMPL123QMS__CAPA__c capaObj = new CMPL123QMS__CAPA__c();
        capaObj.CMPL123QMS__CAPA_Type__c ='Corrective Action';
        capaObj.Short_Description__c ='uTest';
        capaObj.Description__c = 'uTest';
        capaObj.Date_Initiated__c = Date.Today();
        capaObj.Device__c = device.id;
        capaObj.Device_Problem__c = 'Yes';
        capaObj.Health_Risk__c ='Yes';
        capaObj.Business_Risk__c ='High';
        capaObj.Probability_Measure__c = 'Low';
        capaObj.Actual_Risk_Rating__c = 'Low';
        capaObj.Compliance_Risk__c = 'High';
        capaObj.Severity_Measure__c ='High';
        capaObj.Risk_Category__c = 'Low';
        capaObj.Investigation_Required__c = 'Yes';
        capaObj.CAPA_Owner__c = u.id;
        capaObj.Action_Plan__c ='To Test!';
        insert capaObj;
        
        Task tskObj = new Task();
        tskobj.OwnerId = u.id;
        tskObj.Subject ='Call';
        tskObj.Status  ='In Progress';
        tskObj.Priority = 'Normal';
        insert tskObj;
        
        //CAPA Plan Object
        CAPA_Plan__c cPlan = new CAPA_Plan__c();
        cPlan.Name = 'UTest';
        cPlan.CAPA__c = capaObj.Name;
        insert cPlan;
        
        //create a task for the user
        //Task newTask = new Task(Subject='Complete Survey for Transaction');
        Task newTask = new Task(Subject = 'Call',
                                Description = 'Survey Transaction',
                                Priority = 'Normal', 
                                Status = 'In Progress', 
                                IsReminderSet = true, 
                                ReminderDateTime = System.now()+1); 
        
        try{
            insert newTask;
            update tskObj; 
            delete tskObj;
        }
        catch(Exception ex)
        {
            system.debug(ex);
        }
   
    }
    
    @IsTest public static void testCAPAPlanHandlerNegative() {
      // User initialization
        Profile p = [select id from profile where name='Standard User'];

        User u = new User(alias = 'utest', email='utest@email.com',
            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
            localesidkey='en_US', profileid = p.Id, country='United States',
            timezonesidkey='America/Los_Angeles', username='utest789@email.com');
        insert u;
        
        //Devices
        
        CMPL123__Device__c device = new CMPL123__Device__c();
        device.Name = '12345';
        insert device;
        
        //CAPA Object
        CMPL123QMS__CAPA__c capaObj = new CMPL123QMS__CAPA__c();
        capaObj.CMPL123QMS__CAPA_Type__c ='Corrective Action';
        capaObj.Short_Description__c ='uTest';
        capaObj.Description__c = 'uTest';
        capaObj.Date_Initiated__c = Date.Today();
        capaObj.Device__c = device.id;
        capaObj.Device_Problem__c = 'Yes';
        capaObj.Health_Risk__c ='Yes';
        capaObj.Business_Risk__c ='High';
        capaObj.Probability_Measure__c = 'Low';
        capaObj.Actual_Risk_Rating__c = 'Low';
        capaObj.Compliance_Risk__c = 'High';
        capaObj.Severity_Measure__c ='High';
        capaObj.Risk_Category__c = 'Low';
        capaObj.Investigation_Required__c = 'Yes';
        capaObj.CAPA_Owner__c = u.id;
        capaObj.Action_Plan__c ='To Test!';
        insert capaObj;
        
        Task tskObj = new Task();
        tskobj.OwnerId = u.id;
        tskObj.Subject ='Call';
        tskObj.Status  ='In Progress';
        tskObj.Priority = 'Normal';
        insert tskObj;
        
        //CAPA Plan Object
        CAPA_Plan__c cPlan = new CAPA_Plan__c();
        cPlan.Name = 'UTest';
        cPlan.CAPA__c = capaObj.Name;
        insert cPlan;
                
    }
}