objects/Case__x.object
<CustomObject>
    <externalDataSource>BMX_EXTERNAL</externalDataSource>
    <externalName>Case</externalName>
    <fields>
        <fullName>CaseNumber_c__c</fullName>
        <externalDeveloperName>CaseNumber__c</externalDeveloperName>
        <label>SAP Case Number</label>
        <length>12</length>
        <readOnlyProxy>true</readOnlyProxy>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TWComplaintNumber_c__c</fullName>
        <externalDeveloperName>TWComplaintNumber__c</externalDeveloperName>
        <label>TW Complaint Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <externalDeveloperName>Type</externalDeveloperName>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NonQualified</fullName>
                    <label>Non Qualified</label>
                </value>
                <value>
                    <fullName>TechnicalComplaint</fullName>
                    <label>Technical Complaint</label>
                </value>
                <value>
                    <fullName>ServiceComplaint</fullName>
                    <label>Service Complaint</label>
                </value>
                <value>
                    <fullName>CommercialComplaint</fullName>
                    <label>Commercial Complaint</label>
                </value>
                <value>
                    <fullName>Question</fullName>
                </value>
                <value>
                    <fullName>Suggestion</fullName>
                </value>
                <value>
                    <fullName>FieldAction</fullName>
                    <label>Field Action</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case</label>
    <pluralLabel>Case</pluralLabel>
</CustomObject>

objects/CMPL123CME__Complaint__c.object
<CustomObject>
    <fields>
        <fullName>BMX_CaseNumber__c</fullName>
        <label>Case Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BMX_Case_External__c</fullName>
        <label>Case External</label>
        <length>18</length>
        <referenceTo>Case__x</referenceTo>
        <relationshipLabel>Complaint</relationshipLabel>
        <relationshipName>Complaints</relationshipName>
        <type>ExternalLookup</type>
    </fields>
    <fields>
        <fullName>BMX_Case_Type__c</fullName>
        <label>Case Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__CMPL123_WF_Status__c</fullName>
        <label>Workflow Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Ticket No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateNonComplaintForCaseBatch.cls
global class UpdateNonComplaintForCaseBatch implements Database.Batchable<sObject> {
        
        String queryString;
        global Database.QueryLocator start(Database.BatchableContext Bc) {
            
            queryString = ' SELECT Id,CaseNumber_c__c, Type__c,ExternalId,TWComplaintNumber_c__c FROM Case__x WHERE Type__c!=\'TechnicalComplaint\' ';
            system.debug('==queryString=='+queryString); 
            return Database.getQueryLocator(queryString);
        }
        
        global void execute(Database.BatchableContext bc, List<Case__x> caseQuerysObjLst) {
            
            Map < Id,  Case__x > mapCase = new Map < Id, Case__x >();
            List<CMPL123CME__Complaint__c> listComplaints = new List<CMPL123CME__Complaint__c>();
           
            for(Case__x sObj : caseQuerysObjLst){
                mapCase.put(sObj.Id, sObj);             
            }
            
            listComplaints = [SELECT Id,BMX_CaseNumber__c,CMPL123CME__CMPL123_WF_Status__c,BMX_Case_Type__c,BMX_Case_External__c FROM CMPL123CME__Complaint__c WHERE CMPL123CME__CMPL123_WF_Status__c='Opened' AND BMX_Case_External__c IN : mapCase.keySet()];
   
             if(!listComplaints.isEmpty()){
                 
                 for(CMPL123CME__Complaint__c cmp : listComplaints){
                     cmp.CMPL123CME__CMPL123_WF_Status__c='Closed-Canceled';
                     listComplaints.add(cmp);
                 }
            
                update listComplaints;
            }
        }   
            
        
        global void finish(Database.BatchableContext bc){
        
         // execute any post-processing operations like sending email
       }

}