objects/Case__x.object
<CustomObject>
    <externalDataSource>BMX_EXTERNAL</externalDataSource>
    <externalName>Case</externalName>
    <label>Case</label>
    <pluralLabel>Case</pluralLabel>
</CustomObject>

objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>External_Case_Id__c</fullName>
        <label>External Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_ID__c</fullName>
        <label>Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Error Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Appointment__c.object
<CustomObject>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SA_Description__c</fullName>
        <label>SA Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SA_Parent_record__c</fullName>
        <label>SA Parent record</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SA_Status__c</fullName>
        <label>SA Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Dispatched</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>On Site</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cannot Complete</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Rejected by Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>workOrderId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Appointment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ServiceAppointment__x.object
<CustomObject>
    <externalDataSource>BMX_EXTERNAL</externalDataSource>
    <externalName>ServiceAppointment</externalName>
    <fields>
        <fullName>Description__c</fullName>
        <externalDeveloperName>Description</externalDeveloperName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LastModifiedDate__c</fullName>
        <externalDeveloperName>LastModifiedDate</externalDeveloperName>
        <label>Last Modified Date</label>
        <readOnlyProxy>true</readOnlyProxy>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ParentRecordId__c</fullName>
        <externalDeveloperName>ParentRecordId</externalDeveloperName>
        <label>Parent Record ID</label>
        <length>18</length>
        <referenceTo>WorkOrder__x</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments1</relationshipName>
        <type>ExternalLookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <externalDeveloperName>Status</externalDeveloperName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Dispatched</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>On Site</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cannot Complete</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Rejected by Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkOrder_c__c</fullName>
        <externalDeveloperName>WorkOrder__c</externalDeveloperName>
        <label>Work Order</label>
        <length>18</length>
        <referenceTo>WorkOrder__x</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>ExternalLookup</type>
    </fields>
    <label>Service Appointment</label>
    <pluralLabel>Service Appointments</pluralLabel>
</CustomObject>

objects/Work_Order__c.object
<CustomObject>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkOrder__x.object
<CustomObject>
    <fields>
        <fullName>CaseId__c</fullName>
        <externalDeveloperName>CaseId</externalDeveloperName>
        <label>Case</label>
        <length>18</length>
        <referenceTo>Case__x</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>ExternalLookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <externalDeveloperName>Description</externalDeveloperName>
        <label>Description</label>
        <length>32000</length>
        <readOnlyProxy>true</readOnlyProxy>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LastModifiedDate__c</fullName>
        <externalDeveloperName>LastModifiedDate</externalDeveloperName>
        <label>Last Modified Date</label>
        <readOnlyProxy>true</readOnlyProxy>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <externalDeveloperName>Status</externalDeveloperName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cannot Complete</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkOrderNumber__c</fullName>
        <externalDeveloperName>WorkOrderNumber</externalDeveloperName>
        <label>Work Order Number</label>
        <length>255</length>
        <readOnlyProxy>true</readOnlyProxy>
        <type>Text</type>
    </fields>
    <externalDataSource>BMX_EXTERNAL</externalDataSource>
    <externalName>WorkOrder</externalName>
    <label>Work Order</label>
    <pluralLabel>Work Orders</pluralLabel>
</CustomObject>

classes/CreateServiceAppointmentForWorkOrdrBatch.cls
/**
*  --------------------------------------------------------------------------------------------------------------------------------------
* @Who   : Copyright (c) 2017 - 2019  Sparta Systems, Inc.
* @What  : CreateServiceAppointmentForWorkOrdrBatch
* @Why   : Batch class to create Service Appointment custom records from Service Appointment External records and linking them to their respective
*          custom Work Order parent records
* @When  : 14-DEC-2018
  
*  --------------------------------------------------------------------------------------------------------------------------------------
*  Modification Log:  
*  --------------------------------------------------------------------------------------------------------------------------------------
*   Developer                Date             Description 
*  --------------------------------------------------------------------------------------------------------------------------------------
*                        14-DEC-2018        Created.
*  --------------------------------------------------------------------------------------------------------------------------------------
**/

/* */


global class CreateServiceAppointmentForWorkOrdrBatch implements Database.Batchable<SObject>, Database.Stateful,Database.AllowsCallouts{
    private final String VALID_CASE_TYPE = 'TechnicalComplaint';
    
    global CreateServiceAppointmentForWorkOrdrBatch(){}
    Boolean chained;
    DateTime lastExecuted;
    
    //Intializing external Service Appointment Ids in the constructor
    global CreateServiceAppointmentForWorkOrdrBatch(Boolean chain, Datetime lastExecuted){
        this.chained = chain;
        this.lastExecuted = lastExecuted;
    }
    
    // querying the external Service Appointment records
    global Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        if(!Test.isRunningTest()){
             /** We are pulling in Service Appointments associated with recently modified Cases because there is a scenario where a previously
            created Case gets reclassified as a Technical Complaint so we will need to grab the previously created Service Appointments. */
            String formattedTime = lastExecuted.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss.SSSZ');
            return Database.getQueryLocator('SELECT Id,LastModifiedDate__c, WorkOrder_c__r.CaseId__r.Type__c, WorkOrder_c__r.CaseId__r.CaseNumber_c__c, WorkOrder_c__r.CaseId__r.CaseNumber__c, ' +
                                            ' WorkOrder_c__r.CaseId__r.TWComplaintNumber_c__c, WorkOrder_c__r.ExternalId, ExternalId, Description__c,Status__c, ' +
                                            ' ParentRecordId__r.WorkOrderNumber__c FROM ServiceAppointment__x WHERE WorkOrder_c__r.CaseId__r.LastModifiedDate__c >= ' + formattedTime +
                                            ' or LastModifiedDate__c >=' + formattedTime);  
        }else{
            return Database.getQueryLocator('SELECT Id,WorkOrder_c__r.CaseId__r.Type__c, WorkOrder_c__r.CaseId__r.TWComplaintNumber_c__c, WorkOrder_c__r.ExternalId,ExternalId,Description__c,Status__c,' +
                                            'ParentRecordId__r.WorkOrderNumber__c FROM ServiceAppointment__x LIMIT 1');
        }        
    }
    
    global void execute(Database.BatchableContext bc, List<sObject> serviceAppointList){
        
        List<ServiceAppointment__x> records = new List<ServiceAppointment__x>();
        if(!Test.isRunningTest()){
            for(Sobject sObj: serviceAppointList){
                ServiceAppointment__x extServiceAppointObj = (ServiceAppointment__x) sObj;
                if (extServiceAppointObj.WorkOrder_c__r.CaseId__r.CaseNumber_c__c == extServiceAppointObj.WorkOrder_c__r.CaseId__r.CaseNumber__c &&
                   extServiceAppointObj.WorkOrder_c__r.CaseId__r.Type__c == 'TechnicalComplaint') {
                    records.add(extServiceAppointObj);
                }
            }
        }
        
        if(Test.isRunningTest()){
            records.add(BMX_TestDataFactory.getServiceAppointmentExRecord());
        }
        
        List<Service_Appointment__c> serviceApppointmentList = new List<Service_Appointment__c>();
        List<Database.upsertResult> upsertResultList = new List<Database.upsertResult>();
        
        for(ServiceAppointment__x  serviceAppointX: records){
            
            //mapping external Service Appointment fields to the Service Appointment custom object fields to create Service Appointment records
            if(Test.isRunningTest() || 
            (serviceAppointX.WorkOrder_c__r.ExternalId != null && 
            serviceAppointX.WorkOrder_c__r.CaseId__r.Type__c != null &&
            serviceAppointX.WorkOrder_c__r.CaseId__r.Type__c == VALID_CASE_TYPE &&
            (  serviceAppointX.WorkOrder_c__r.CaseId__r.TWComplaintNumber_c__c == null ||
             serviceAppointX.WorkOrder_c__r.CaseId__r.TWComplaintNumber_c__c.contains('CN') ))){
                Service_Appointment__c serviceAppoint = new Service_Appointment__c();
                serviceAppoint.workOrderId__r = new Work_Order__c(ExternalId__c = serviceAppointX.WorkOrder_c__r.ExternalId);
                serviceAppoint.ExternalId__c = serviceAppointX.ExternalId;
                serviceAppoint.SA_Description__c = serviceAppointX.Description__c;
                serviceAppoint.SA_Parent_record__c = serviceAppointX.ParentRecordId__r.WorkOrderNumber__c;
                serviceAppoint.SA_Status__c = serviceAppointX.Status__c;                        
                serviceApppointmentList.add(serviceAppoint);
            }
        }
        
        
        System.debug('-------serviceApppointmentList------'+serviceApppointmentList);
        
        if(!serviceApppointmentList.isEmpty()) {
        
            // Upserting the external Service Appointment list of records
            upsertResultList = Database.Upsert(serviceApppointmentList,Service_Appointment__c.ExternalId__c, false);
        }
        
        // creating error log records if any record gets failed during the execution of the batch
        if(!upsertResultList.isEmpty()) {
            List<Error_Log__c> errLogList = new List<Error_Log__c>();
            for(Integer i=0; i <upsertResultList.size(); i++) {
                if(!upsertResultList[i].isSuccess() ) {
                    Error_Log__c el = Utils_CreateComplaintForCaseBatch.returnErrorLog(upsertResultList[i].getErrors(), 
                                                                                       'CreateServiceAppointmentForWorkOrdrBatch', 'Service_Appointment__c');
                    el.Record_ID__c = serviceApppointmentList[i].Id;
                    el.External_Case_Id__c = serviceApppointmentList[i].ExternalId__c;
                    errLogList.add(el);
                }
            }
            if(!errLogList.isEmpty()) {
                Database.Insert(errLogList, false);
            }
        } 
    }  
    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
        system.debug('Service Appointments inserted/updated');
    } 
}