objects/Case__x.object
<CustomObject>
    <externalDataSource>BMX_EXTERNAL</externalDataSource>
    <externalName>Case</externalName>
    <fields>
        <fullName>CreatedById__c</fullName>
        <externalDeveloperName>CreatedById</externalDeveloperName>
        <label>Created By ID</label>
        <length>18</length>
        <referenceTo>User__x</referenceTo>
        <relationshipLabel>Case</relationshipLabel>
        <relationshipName>Case4</relationshipName>
        <type>ExternalLookup</type>
    </fields>
    <fields>
        <fullName>CreatedDate__c</fullName>
        <externalDeveloperName>CreatedDate</externalDeveloperName>
        <label>Created Date</label>
        <readOnlyProxy>true</readOnlyProxy>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LastModifiedDate__c</fullName>
        <externalDeveloperName>LastModifiedDate</externalDeveloperName>
        <label>Last Modified Date</label>
        <readOnlyProxy>true</readOnlyProxy>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ParentId__c</fullName>
        <externalDeveloperName>ParentId</externalDeveloperName>
        <label>Parent Case ID</label>
        <length>18</length>
        <referenceTo>Case__x</referenceTo>
        <relationshipLabel>Case</relationshipLabel>
        <relationshipName>Case</relationshipName>
        <type>ExternalLookup</type>
    </fields>
    <label>Case</label>
    <pluralLabel>Case</pluralLabel>
</CustomObject>

objects/Case_Comment__c.object
<CustomObject>
    <fields>
        <fullName>BMX_User__c</fullName>
        <label>User</label>
        <length>18</length>
        <referenceTo>User__x</referenceTo>
        <relationshipLabel>Case Comments</relationshipLabel>
        <relationshipName>Case_Comment</relationshipName>
        <type>ExternalLookup</type>
    </fields>
    <fields>
        <fullName>CommentBody__c</fullName>
        <label>CommentBody</label>
        <length>40000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ComplaintId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Complaint</label>
        <referenceTo>CMPL123CME__Complaint__c</referenceTo>
        <relationshipLabel>Case Comments</relationshipLabel>
        <relationshipName>Case_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <label>Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Case Comment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CaseComment__x.object
<CustomObject>
    <fields>
        <fullName>CommentBody__c</fullName>
        <externalDeveloperName>CommentBody</externalDeveloperName>
        <label>Body</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CreatedById__c</fullName>
        <externalDeveloperName>CreatedById</externalDeveloperName>
        <label>Created By ID</label>
        <length>18</length>
        <referenceTo>User__x</referenceTo>
        <relationshipLabel>Case Comments</relationshipLabel>
        <relationshipName>Case_Comments</relationshipName>
        <type>ExternalLookup</type>
    </fields>
    <fields>
        <fullName>CreatedDate__c</fullName>
        <externalDeveloperName>CreatedDate</externalDeveloperName>
        <label>Created Date</label>
        <readOnlyProxy>true</readOnlyProxy>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LastModifiedDate__c</fullName>
        <externalDeveloperName>LastModifiedDate</externalDeveloperName>
        <label>Last Modified Date</label>
        <readOnlyProxy>true</readOnlyProxy>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ParentId__c</fullName>
        <externalDeveloperName>ParentId</externalDeveloperName>
        <label>Parent ID</label>
        <length>18</length>
        <referenceTo>Case__x</referenceTo>
        <relationshipLabel>Case Comments</relationshipLabel>
        <relationshipName>Case_Comments</relationshipName>
        <type>ExternalLookup</type>
    </fields>
    <externalDataSource>BMX_EXTERNAL</externalDataSource>
    <externalName>CaseComment</externalName>
    <label>Case Comment</label>
    <pluralLabel>Case Comments</pluralLabel>
</CustomObject>

objects/CMPL123CME__Complaint__c.object
<CustomObject>
    <fields>
        <fullName>BMX_Case_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Case External Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BMX_Case_External__c</fullName>
        <label>Case External</label>
        <length>18</length>
        <referenceTo>Case__x</referenceTo>
        <relationshipLabel>Complaint</relationshipLabel>
        <relationshipName>Complaints</relationshipName>
        <type>ExternalLookup</type>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Ticket No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Complaint_Creation_Batch_Time__c.object
<CustomObject>
    <fields>
        <fullName>Time_Interval__c</fullName>
        <label>Time Interval</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Complaint Creation Batch Time</label>
</CustomObject>

objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>External_Case_Id__c</fullName>
        <label>External Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_ID__c</fullName>
        <label>Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Error Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User__x.object
<CustomObject>
    <externalDataSource>BMX_EXTERNAL</externalDataSource>
    <externalName>User</externalName>
    <fields>
        <fullName>CreatedById__c</fullName>
        <externalDeveloperName>CreatedById</externalDeveloperName>
        <label>Created By ID</label>
        <length>18</length>
        <readOnlyProxy>true</readOnlyProxy>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CreatedDate__c</fullName>
        <externalDeveloperName>CreatedDate</externalDeveloperName>
        <label>Created Date</label>
        <readOnlyProxy>true</readOnlyProxy>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LastModifiedDate__c</fullName>
        <externalDeveloperName>LastModifiedDate</externalDeveloperName>
        <label>Last Modified Date</label>
        <readOnlyProxy>true</readOnlyProxy>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <externalDeveloperName>Name</externalDeveloperName>
        <label>Full Name</label>
        <length>121</length>
        <readOnlyProxy>true</readOnlyProxy>
        <type>Text</type>
    </fields>
    <label>User</label>
    <pluralLabel>Users</pluralLabel>
</CustomObject>

classes/CreateCaseCommentForComplaintBatch.cls
/**
*  --------------------------------------------------------------------------------------------------------------------------------------
* @Who   : Copyright (c) 2017 - 2019  Sparta Systems, Inc.
* @What  : CreateAllChildSchedulableBatch
* @Why   : Batch class to create Case Comment custom records from Case Comment External records and linking them to their respective complaints
* @When  : 14-DEC-2018
  
*  --------------------------------------------------------------------------------------------------------------------------------------
*  Modification Log:  
*  --------------------------------------------------------------------------------------------------------------------------------------
*   Developer                Date             Description 
*  --------------------------------------------------------------------------------------------------------------------------------------
*                        14-DEC-2018        Created.
*  --------------------------------------------------------------------------------------------------------------------------------------
**/

global virtual class CreateCaseCommentForComplaintBatch implements Database.Batchable<sObject>, Database.Stateful,Database.AllowsCallouts{
    
    //Intializing external Case Comment Ids in the constructor
    global CreateCaseCommentForComplaintBatch(){}
    Boolean chained;
    global CreateCaseCommentForComplaintBatch(Boolean chain){
        this.chained = chain;
    }
    
    // querying the external Case Comment records
    global virtual Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        DateTime dt = System.now().addHours(-24);
        Integer count = [SELECT count() FROM CaseComment__x WHERE LastModifiedDate__c >=: dt];
        
        if(!Test.isRunningTest()){
            return Database.getQueryLocator('SELECT Id,CommentBody__c,ParentId__r.ExternalId,CreatedById__r.Name__c,ExternalId,CreatedDate__c FROM CaseComment__x ORDER BY LastModifiedDate__c DESC LIMIT ' + count);   
        }else{
            return Database.getQueryLocator('SELECT Id FROM Case LIMIT 1');
        }
        
        
    }
    
    global void execute(Database.BatchableContext bc, List<sObject> CaseCommList){
        
        List<CaseComment__x> records = new List<CaseComment__x>();
        if(!Test.isRunningTest()){
            for(Sobject sObj: CaseCommList){
                CaseComment__x extCaseCommObj = (CaseComment__x) sObj;
                records.add(extCaseCommObj);
            }
        }
        
        if(Test.isRunningTest()){
            records.add(BMX_TestDataFactory.getCaseCommentExRecord());
        }
        system.debug('==case comment records====='+records);
        List<Case_Comment__c> caseCommentList = new List<Case_Comment__c>();
        List<Database.upsertResult> upsertResultList = new List<Database.upsertResult>();
        /*Set<Id> caseExIdSet = new Set<Id>();
Map<Id, CMPL123CME__Complaint__c> cmpMap = new Map<Id, CMPL123CME__Complaint__c>();

for(CaseComment__x  caseCommX : records) {
caseExIdSet.add(caseCommX.ParentId__r.ExternalId);
}

for(CMPL123CME__Complaint__c cmp : [SELECT Id, BMX_Case_External__c FROM CMPL123CME__Complaint__c WHERE BMX_Case_External__c IN: caseExIdSet]) {
cmpMap.put(cmp.BMX_Case_External__c, cmp);
}*/
        
        for(CaseComment__x  caseCommX: records){
            
            //mapping external Case Comment fields to the Case Comment custom object fields to create Case Comment records
            if(Test.isRunningTest() || caseCommX.ParentId__r.ExternalId != null){
                //Integer cmplntCount = (!Test.isRunningTest()) ? [SELECT Count() FROM CMPL123CME__Complaint__c WHERE BMX_Case_External_Id__c =: caseCommX.ParentId__r.ExternalId LIMIT 1] : 1;
                Case_Comment__c caseComm = new Case_Comment__c();
                caseComm.ComplaintId__r = new CMPL123CME__Complaint__c(BMX_Case_External_Id__c = caseCommX.ParentId__r.ExternalId);
                //caseComm.ComplaintId__c = cmpMap.get(caseCommX.ParentId__r.ExternalId).Id;
                caseComm.CommentBody__c = caseCommX.CommentBody__c;
                caseComm.ExternalId__c = caseCommX.ExternalId;
                caseComm.BMX_User__c = caseCommX.CreatedById__c;
                caseComm.Created_Date__c = caseCommX.CreatedDate__c;
                caseCommentList.add(caseComm);
                
            }
        }
        
        System.debug('-------caseCommentList------'+caseCommentList);
        
        if(!caseCommentList.isEmpty()) {
		
			// Upserting the external Case Comment list of records
            upsertResultList = Database.Upsert(caseCommentList,Case_Comment__c.ExternalId__c, false);
        }
        
		// creating error log records if any record gets failed during the execution of the batch
        if(!upsertResultList.isEmpty()) {
            List<Error_Log__c> errLogList = new List<Error_Log__c>();
            for(Integer i=0; i <upsertResultList.size(); i++) {
                if(!upsertResultList[i].isSuccess() ) {
                    Error_Log__c el = Utils_CreateComplaintForCaseBatch.returnErrorLog(upsertResultList[i].getErrors(), 
                                                                                       'CreateCaseCommentForComplaintBatch', 'Case_Comment__c');
                    el.Record_ID__c = caseCommentList[i].Id;
                    el.External_Case_Id__c = caseCommentList[i].ExternalId__c;
                    errLogList.add(el);
                }
            }
            if(!errLogList.isEmpty()) {
                Database.Insert(errLogList, false);
            }
        }
    }  
    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing
        //system.debug('Case Comments inserted/updated');
        //if(chained) {
        //Complaint_Creation_Batch_Time__c cs = Complaint_Creation_Batch_Time__c.getInstance();
        //Integer gap = Integer.valueOf(cs.Time_Interval__c);
        
        //dateTime timeInterval  = System.now().addMinutes(gap);
        //String cronExp = '0 ' + timeInterval.minute() + ' ' + timeInterval.hour() + ' ' + timeInterval.day() + ' ' + timeInterval.month() + ' ?';
        //System.schedule('Case External Sync Job ' + timeInterval, cronExp, new CreateAllChildSchedulableBatch());
        if(!Test.isRunningTest()){
		
		    // Executing the CreateWorkOrderForComplaintBatch batch class
            CreateWorkOrderForComplaintBatch createWorkOrder = new CreateWorkOrderForComplaintBatch(true);
            database.executebatch(createWorkOrder);
        }
        
        //}  
    } 
}