objects/CMPL123CME__Complaint__c.object
<CustomObject>
    <fields>
        <fullName>BMX_Batch_Expiration_Date__c</fullName>
        <label>Batch Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BMX_Batch_Number_Reagent__c</fullName>
        <label>Batch Number (Reagent)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BMX_Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>BMX_Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BMX_Contact_Phone__c</fullName>
        <label>Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>BMX_Customer_Contact_Date__c</fullName>
        <label>Customer Contact Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BMX_PRE1_Patient_or_operator_death__c</fullName>
        <label>PRE1.1 Patient or operator death?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BMX_PRE2_1_Patient_or_operator_harmed__c</fullName>
        <label>PRE2.1 Patient or operator harmed?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BMX_Product_Code__c</fullName>
        <inlineHelpText>Correspond to Product Code for Product, whatever it’s an instrument or a reagent</inlineHelpText>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BMX_Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BMX_Reference__c</fullName>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BMX_Serial_Number_Asset__c</fullName>
        <label>Serial Number (Asset)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Device Malfunction</fullName>
                </value>
                <value>
                    <fullName>Shipment Error</fullName>
                </value>
                <value>
                    <fullName>Adverse Event</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visitor_Address_Name__c</fullName>
        <label>Visitor Address Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visitor_City__c</fullName>
        <label>Visitor City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visitor_Country__c</fullName>
        <label>Visitor Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visitor_Postal_Code__c</fullName>
        <label>Visitor PostalCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visitor_Street__c</fullName>
        <label>Visitor Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Ticket No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMPL123CME__Complaint_Code__c.object
<CustomObject>
    <description>Code Name</description>
    <fields>
        <fullName>CMPL123CME__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SYMPTOM CODE</fullName>
                </value>
                <value>
                    <fullName>ANALYSIS CODE</fullName>
                </value>
                <value>
                    <fullName>PATIENT CODE</fullName>
                </value>
                <value>
                    <fullName>DEVICE CODE</fullName>
                </value>
                <value>
                    <fullName>EVAL METHOD CODE</fullName>
                </value>
                <value>
                    <fullName>EVAL RESULT CODE</fullName>
                </value>
                <value>
                    <fullName>EVAL CONCLUSION CODE</fullName>
                </value>
                <value>
                    <fullName>COMPLAINT CODE</fullName>
                </value>
                <value>
                    <fullName>ROOT CAUSE CODE</fullName>
                </value>
                <value>
                    <fullName>FINDING CODE</fullName>
                </value>
                <value>
                    <fullName>MEDDRA CODE</fullName>
                </value>
                <value>
                    <fullName>COMPONENT CODE</fullName>
                </value>
                <value>
                    <fullName>COUNTRY CODE</fullName>
                </value>
                <value>
                    <fullName>STATE CODE</fullName>
                </value>
                <value>
                    <fullName>PRO CODE</fullName>
                </value>
                <value>
                    <fullName>HEALTH EFFECT - CLINICAL CODE</fullName>
                </value>
                <value>
                    <fullName>HEALTH EFFECT - IMPACT CODE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Local_Subsidiary_Text__c</fullName>
        <label>Local Subsidiary</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Complaint Code</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Complaint Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMPL123CME__MEDDEV__c.object
<CustomObject>
    <fields>
        <fullName>CMPL123CME__Complaint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Complaint</description>
        <inlineHelpText>Related Complaint</inlineHelpText>
        <label>Complaint</label>
        <referenceTo>CMPL123CME__Complaint__c</referenceTo>
        <relationshipLabel>MEDDEV</relationshipLabel>
        <relationshipName>MEDDEV</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Type_of_Report__c</fullName>
        <description>Type of report</description>
        <inlineHelpText>Type of report</inlineHelpText>
        <label>Type of report</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial report</fullName>
                </value>
                <value>
                    <fullName>Follow-up report</fullName>
                </value>
                <value>
                    <fullName>Combined initial and final report</fullName>
                </value>
                <value>
                    <fullName>Final report</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Local_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Assessment</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CMPL123CME__Questionnaire__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Local Assessment</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CMPL123CME__Questionnaire__c</referenceTo>
        <relationshipLabel>MEDDEV</relationshipLabel>
        <relationshipName>MEDDEV</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Local_Subsidiary_Text__c</fullName>
        <label>Local Subsidiary</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>Medical Devices Vigilance System</description>
    <label>MEDDEV</label>
    <nameField>
        <displayFormat>MD{0000}</displayFormat>
        <label>Incident Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MEDDEV</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CMPL123CME__Questionnaire__c.object
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Questionnaire No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Complaint</fullName>
        <active>true</active>
        <label>Complaint</label>
    </recordTypes>
</CustomObject>

classes/CMPLCMPL123CMEMEDDEVTriggerTest.cls
@isTest
public   class CMPLCMPL123CMEMEDDEVTriggerTest{
    static testMethod void CMPL123CMEMEDDEVTriggerTestmethod(){
        
        CMPL123CME__Complaint__c complaint = new CMPL123CME__Complaint__c(
            BMX_Reference__c = 'test',BMX_Product_Code__c = 'test',BMX_Product_Name__c = 'test',BMX_Contact_Name__c = 'test',
            BMX_Batch_Expiration_Date__c = Date.newInstance(2018, 12, 8), Visitor_Street__c = 'test',Visitor_City__c = 'test',
            BMX_Contact_Email__c = 'a@test.com',BMX_Contact_Phone__c = '1234567',Visitor_Postal_Code__c = '560066', 
            Visitor_Country__c = 'India',BMX_Batch_Number_Reagent__c ='2345',BMX_Customer_Contact_Date__c = Date.newInstance(2018, 10, 8),
            Visitor_Address_Name__c = 'test',BMX_Serial_Number_Asset__c = '123',BMX_PRE1_Patient_or_operator_death__c = 'Yes',
        BMX_PRE2_1_Patient_or_operator_harmed__c  = 'Yes');
        insert complaint;
        
        CMPL123CME__Complaint_Code__c cmplntCode = new CMPL123CME__Complaint_Code__c(Local_Subsidiary_Text__c = 'test',
                                                                                    CMPL123CME__Type__c = 'COUNTRY CODE');
        insert cmplntCode;
        
        String globalRTId = Schema.SObjectType.CMPL123CME__Questionnaire__c.getRecordTypeInfosByName().get('Global Assessment').getRecordTypeId();
        CMPL123CME__Questionnaire__c globalRecord = new CMPL123CME__Questionnaire__c();
        globalRecord.RecordTypeId = globalRTId;
        globalRecord.BMX_Title__c = 'Global12345';
        globalRecord.CMPL123CME__Complaint__c = complaint.Id;
        globalRecord.BMX_Description_of_Issue__c = 'test';
        globalRecord.Local_Subsidiary_Text__c = 'test';
        globalRecord.BMX_Revised_Awareness_Date__c = Date.newInstance(2018, 12, 8);
        globalRecord.BMX_Justification_of_Due_Date_Change__c = 'test';
        insert globalRecord;
        system.debug('==globalRecord=='+globalRecord);
        
        String localRTId = Schema.SObjectType.CMPL123CME__Questionnaire__c.getRecordTypeInfosByName().get('Local Assessment').getRecordTypeId();
        CMPL123CME__Questionnaire__c localRecord = new CMPL123CME__Questionnaire__c();
        localRecord.RecordTypeId = localRTId;
        localRecord.BMX_Global_Assessment__c = globalRecord.Id;
        localRecord.BMX_Reportable_Country2__c = cmplntCode.Id;
        localRecord.BMX_Justification_of_Report_Due_Change__c = 'test';
        system.debug('==localRecord=='+localRecord);
        insert localRecord;
        
        
        CMPL123CME__MEDDEV__c testobject = new CMPL123CME__MEDDEV__c ();
        testobject.Local_Assessment__c = localRecord.Id;
        testobject.CMPL123CME__Type_of_Report__c = 'Initial report';
        //testobject.CMPL123CME__Complaint__c = complaint.Id;
        insert testobject; 
        delete testobject;
        undelete testobject;                                      
        update testobject; 
        System.assertEquals('1','1');
    }
}