objects/CMPL123QMS__Change_Control__c.object
<CustomObject>
    <label>Change Control</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Change Control Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Control</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Extension_Request_Change_Control__c.object
<CustomObject>
    <fields>
        <fullName>Change_Control__c</fullName>
        <label>Change Control</label>
        <referenceTo>CMPL123QMS__Change_Control__c</referenceTo>
        <relationshipLabel>Extension Requests Change Control</relationshipLabel>
        <relationshipName>Extension_Requests_Change_Control</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Extension Request Change Control</label>
    <nameField>
        <displayFormat>ER-CC-{00000}</displayFormat>
        <label>ER-CC No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Extension Requests Change Control</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Extension_Req_Change_CtrlTriggerTest.cls
@isTest
 public   class Extension_Req_Change_CtrlTriggerTest{
	static testMethod void Extension_Request_Change_ControlTriggerTestmethod(){
        
        CMPL123QMS__Change_Control__c changeCtrl = new CMPL123QMS__Change_Control__c();
        insert changeCtrl;
		Extension_Request_Change_Control__c testobject = new Extension_Request_Change_Control__c (Change_Control__c = changeCtrl.Id);
		insert testobject; 
		delete testobject; 
		undelete testobject; 
		update testobject; 
		System.assertEquals('1','1');
	}
}