objects/CMPL123CME__EU_MIR__c.object
<CustomObject>
    <description>European Manufacturer Incident Report</description>
    <fields>
        <fullName>CMPL123CME__Explain_If_Investigation_Code_Missing__c</fullName>
        <description>If you think the incident is unique and a suitable IMDRF Investigation code is missing, briefly explain.</description>
        <inlineHelpText>If you think the incident is unique and a suitable IMDRF Investigation code is missing, briefly explain.</inlineHelpText>
        <label>Explain if Investigation Code missing</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Manufacturer_s_Evaluation__c</fullName>
        <description>A report of your analysis of the device involved in this event. If no analysis or investigation of the device could be carried out, for example if the device was not returned, then indicate the most probable root cause analysis. Please be clear whether you are describing the root cause or most probable root cause.
In many cases, evaluation of the actual device is not feasible. Instead the investigation may focus on "surrogate devices", i.e. devices belong to the same batch or lot as the device, to another lot/batch. Testing of model variants may also be indicated in specific cases. Please describe the devices investigated &amp; if applicable, tested-- Other investigative means than testing may include interviews with the user/operator of the device, control of production records etc. Your investigations and conclusions should be explained and their credibility and plausibility justified.
If you refer to an existing CAPA please provide the reference or identification number of that CAPA.</description>
        <inlineHelpText>A report of your analysis of the device involved in this event. If no analysis or investigation of the device could be carried out, for example if the device was not returned, then indicate the most probable root cause analysis.</inlineHelpText>
        <label>Manufacturer Evaluation Final Report</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMPL123_WF_Status__c</fullName>
        <label>Workflow Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>EU MIR</label>
    <nameField>
        <displayFormat>EU-MIR-{000000}</displayFormat>
        <label>EU MIR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EU MIR</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CMPL123CME__Investigation__c.object
<CustomObject>
    <description>INVESTIGATION AND ROOT CAUSE INFORMATION</description>
    <fields>
        <fullName>BMX_Investigation_Answer__c</fullName>
        <label>Investigation Answer</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>B_Investigation_Type_Code_Choice_1__c</fullName>
        <label>Type/Method Choice 1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>B_Choice</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>B_Investigation_Type_Code_Choice_2__c</fullName>
        <label>Type/Method Choice 2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>B_Choice</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>B_Investigation_Type_Code_Choice_3__c</fullName>
        <label>Type/Method Choice 3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>B_Choice</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>B_Investigation_Type_Code_Choice_4__c</fullName>
        <label>Type/Method Choice 4</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>B_Choice</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>B_Investigation_Type_Code_Choice_5__c</fullName>
        <label>Type/Method Choice 5</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>B_Choice</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>B_Investigation_Type_Code_Choice_6__c</fullName>
        <label>Type/Method Choice 6</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>B_Choice</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CMPL123_WF_Status__c</fullName>
        <label>Workflow Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>C_Investigation_Findings_Code_Choice1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Findings/Results Choice 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CMPL123CME__EU_MIR_Code__c.Name</field>
                <operation>startsWith</operation>
                <value>C</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CMPL123CME__EU_MIR_Code__c</referenceTo>
        <relationshipLabel>Investigations/Evaluations</relationshipLabel>
        <relationshipName>Investigations_Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>C_Investigation_Findings_Code_Choice2__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Findings/Results Choice 2</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CMPL123CME__EU_MIR_Code__c.Name</field>
                <operation>startsWith</operation>
                <value>C</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CMPL123CME__EU_MIR_Code__c</referenceTo>
        <relationshipLabel>Investigations/Evaluations (C-Investigation Findings Code-Choice 2)</relationshipLabel>
        <relationshipName>Investigations_Evaluations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>C_Investigation_Findings_Code_Choice3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Findings/Results Choice 3</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CMPL123CME__EU_MIR_Code__c.Name</field>
                <operation>startsWith</operation>
                <value>C</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CMPL123CME__EU_MIR_Code__c</referenceTo>
        <relationshipLabel>Investigations/Evaluations (C-Investigation Findings Code-Choice 3)</relationshipLabel>
        <relationshipName>Investigations_Evaluations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>D_Investigation_Conclusion_Choice1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Root Cause/Conclusion Choice  1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CMPL123CME__EU_MIR_Code__c.Name</field>
                <operation>startsWith</operation>
                <value>D</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>CMPL123CME__EU_MIR_Code__c</referenceTo>
        <relationshipLabel>Investigations/Evaluations (D-Investigation Conclusion-Choice 1)</relationshipLabel>
        <relationshipName>D_Choice1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>D_Investigation_Conclusion_Choice2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Root Cause/Conclusion Choice  2</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CMPL123CME__EU_MIR_Code__c.Name</field>
                <operation>startsWith</operation>
                <value>D</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>CMPL123CME__EU_MIR_Code__c</referenceTo>
        <relationshipLabel>Investigations/Evaluations (D-Investigation Conclusion-Choice 2)</relationshipLabel>
        <relationshipName>Investigations_Evaluations3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>D_Investigation_Conclusion_Choice3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Root Cause/Conclusion Choice  3</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CMPL123CME__EU_MIR_Code__c.Name</field>
                <operation>startsWith</operation>
                <value>D</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>CMPL123CME__EU_MIR_Code__c</referenceTo>
        <relationshipLabel>Investigations/Evaluations (D-Investigation Conclusion-Choice 3)</relationshipLabel>
        <relationshipName>Investigations_Evaluations4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EU_MIR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EU MIR</label>
        <referenceTo>CMPL123CME__EU_MIR__c</referenceTo>
        <relationshipLabel>Investigations/Evaluations</relationshipLabel>
        <relationshipName>Investigations_Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Justification_for_Annex_B__c</fullName>
        <inlineHelpText>This field is mandatory if you have not select the most detailed level for Type/Method</inlineHelpText>
        <label>Justification for Annex B</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Justification_for_Annex_C__c</fullName>
        <inlineHelpText>This field is mandatory if you have not select the most detailed level for Findings/Results</inlineHelpText>
        <label>Justification for Annex C</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Justification_for_Annex_D__c</fullName>
        <inlineHelpText>This field is mandatory if you have not select the most detailed level for Root Cause/Conclusion</inlineHelpText>
        <label>Justification for Annex D</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Investigation</label>
        <referenceTo>CMPL123CME__Investigation__c</referenceTo>
        <relationshipLabel>Referenced Investigations/Evaluations</relationshipLabel>
        <relationshipName>Investigations_Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Investigation/Evaluation</label>
    <nameField>
        <label>Investigation/Evaluation Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investigations/Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/B_Choice.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>B01 - Testing of Actual/Suspected Device</fullName>
    </customValue>
    <customValue>
        <fullName>B02 - Testing of Device from Same Lot/Batch Retained by Manufacturer</fullName>
    </customValue>
    <customValue>
        <fullName>B03 - Testing of Device from Same Lot/Batch Returned from User</fullName>
    </customValue>
    <customValue>
        <fullName>B04 - Testing of Device from Other Lot/Batch Retained by Manufacturer</fullName>
    </customValue>
    <customValue>
        <fullName>B05 - Testing of Device from Other Lot/Batch Returned From User</fullName>
    </customValue>
    <customValue>
        <fullName>B06 - Testing of Model Variant</fullName>
    </customValue>
    <customValue>
        <fullName>B07 - Testing of Raw/Starting Materials</fullName>
    </customValue>
    <customValue>
        <fullName>B08 - Testing of Patient Sample or Reference Material Using Manufacturer&apos;s Device</fullName>
    </customValue>
    <customValue>
        <fullName>B09 - Testing of Patient Sample or Reference Material Using Reference Method</fullName>
    </customValue>
    <customValue>
        <fullName>B10 - Testing of Patient Sample or Reference Material Using Competitor&apos;s Device</fullName>
    </customValue>
    <customValue>
        <fullName>B11 - Historical Data Analysis</fullName>
    </customValue>
    <customValue>
        <fullName>B12 - Trend Analysis</fullName>
    </customValue>
    <customValue>
        <fullName>B13 - Communication/Interviews</fullName>
    </customValue>
    <customValue>
        <fullName>B14 - Analysis of Production Records</fullName>
    </customValue>
    <customValue>
        <fullName>B15 - Analysis of Data Provided by User/Third Party</fullName>
    </customValue>
    <customValue>
        <fullName>B16 - Device Not Manufactured by Reporting Manufacturer</fullName>
    </customValue>
    <customValue>
        <fullName>B17 - Device Not Returned</fullName>
    </customValue>
    <customValue>
        <fullName>B18 - Device Discarded</fullName>
    </customValue>
    <customValue>
        <fullName>B19 - Incomplete Device Returned</fullName>
    </customValue>
    <customValue>
        <fullName>B20 - Device Not Accessible for Testing</fullName>
    </customValue>
    <customValue>
        <fullName>B21 - Type of Investigation Not Yet Determined</fullName>
    </customValue>
    <customValue>
        <fullName>B22 - Insufficient Information Available</fullName>
    </customValue>
    <masterLabel>B-Choice</masterLabel>
</GlobalValueSet>

classes/Childinvest_Eumir_Update.cls
public class Childinvest_Eumir_Update
{
    //@InvocableMethod
    public static void ChildInvest_JustificationUpdate(List<CMPL123CME__Investigation__c> InvestList) 
    {
        map<Id,CMPL123CME__Investigation__c> MIRInvestmap= new map<Id,CMPL123CME__Investigation__c>();
        
        List<CMPL123CME__Investigation__c> Childinvrecords = [SELECT id,CMPL123_WF_Status__c,EU_MIR__c,BMX_Investigation_Answer__c,Justification_for_Annex_B__c,Justification_for_Annex_C__c,Justification_for_Annex_D__c,B_Investigation_Type_Code_Choice_1__c,B_Investigation_Type_Code_Choice_2__c,B_Investigation_Type_Code_Choice_3__c,B_Investigation_Type_Code_Choice_4__c,B_Investigation_Type_Code_Choice_5__c,B_Investigation_Type_Code_Choice_6__c,C_Investigation_Findings_Code_Choice1__c,C_Investigation_Findings_Code_Choice2__c,C_Investigation_Findings_Code_Choice3__c,D_Investigation_Conclusion_Choice1__c,D_Investigation_Conclusion_Choice2__c,D_Investigation_Conclusion_Choice3__c FROM CMPL123CME__Investigation__c WHERE Master_Investigation__c IN: InvestList];
        system.debug('MS::ChildInvestlist::'+Childinvrecords);
        
        for(CMPL123CME__Investigation__c inv :Childinvrecords)   
        {
           
          if(inv.CMPL123_WF_Status__c  == 'Closed - Done')
          {           
                if(String.isNotBlank(inv.Justification_for_Annex_B__c) || String.isNotBlank(inv.Justification_for_Annex_C__c) || String.isNotBlank(inv.Justification_for_Annex_D__c))
                {            
                    MIRInvestmap.put(inv.EU_MIR__c,inv);
                }
                
          }
        }
        
        system.debug('MIRInvestmap::'+MIRInvestmap);
        system.debug('Childinvrecords MSR::'+Childinvrecords);
        
        List<CMPL123CME__EU_MIR__c> EMIRlistupdt= new List<CMPL123CME__EU_MIR__c>();
            if(!MIRInvestmap.isEmpty())
            {
                List<CMPL123CME__EU_MIR__c> EMIRlist=[select id,CMPL123CME__Explain_If_Investigation_Code_Missing__c,CMPL123CME__Manufacturer_s_Evaluation__c from CMPL123CME__EU_MIR__c where Id IN:MIRInvestmap.keyset()];
                for(CMPL123CME__EU_MIR__c emr: EMIRlist)
                {
                    CMPL123CME__EU_MIR__c mr= new CMPL123CME__EU_MIR__c();
                    mr.Id=emr.Id;
                   // mr.CMPL123CME__Explain_If_Investigation_Code_Missing__c= MIRInvestmap.get(emr.Id).Justification_for_Annex_B__c+MIRInvestmap.get(emr.Id).Justification_for_Annex_C__c+MIRInvestmap.get(emr.Id).Justification_for_Annex_D__c;
                    mr.CMPL123CME__Explain_If_Investigation_Code_Missing__c= ((MIRInvestmap.get(emr.Id).Justification_for_Annex_B__c==null)?'':MIRInvestmap.get(emr.Id).Justification_for_Annex_B__c)+' '+'/'+' '+((MIRInvestmap.get(emr.Id).Justification_for_Annex_C__c==null)?'':MIRInvestmap.get(emr.Id).Justification_for_Annex_C__c)+' '+'/'+' '+((MIRInvestmap.get(emr.Id).Justification_for_Annex_D__c==null)?'':MIRInvestmap.get(emr.Id).Justification_for_Annex_D__c);
                    mr.CMPL123CME__Manufacturer_s_Evaluation__c=MIRInvestmap.get(emr.Id).BMX_Investigation_Answer__c;
                    EMIRlistupdt.add(mr);
                }
            }
            system.debug('EMIRlistupdt MSR::'+EMIRlistupdt);
            if(!EMIRlistupdt.isEmpty())
            {
                update EMIRlistupdt;
            }
    }
    
   /** public class ChildInvestWrapper{
    
        @InvocableVariable
        public Id ChildInvestId;
   ***/
   
    }