objects/CMPL123QMS__CAPA__c.object
<CustomObject>
    <fields>
        <fullName>CMPL123_WF_Status__c</fullName>
        <label>Workflow Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CAPA</label>
    <nameField>
        <displayFormat>CAPA-{00000}</displayFormat>
        <label>CAPA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CAPAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CAPAValidation_Test.cls
@isTest
public class CAPAValidation_Test {
    
    public Static testMethod void capaValidationTriggerTest(){ 
        
        CMPL123QMS__CAPA__c capaRec = new CMPL123QMS__CAPA__c();
        capaRec.CMPL123_WF_Status__c = 'Pending Approval - CAPA Action Plan';
        insert capaRec;
        update capaRec;
        
        CMPL123QMS__CAPA__c capaRec1 = new CMPL123QMS__CAPA__c();
        capaRec1.CMPL123_WF_Status__c = 'Completed - Done';
        insert capaRec1;
        update capaRec1;
        
        CMPL123QMS__CAPA__c capaRec2 = new CMPL123QMS__CAPA__c();
        capaRec1.CMPL123_WF_Status__c = 'In Planning - CAPA';
        insert capaRec2;
        update capaRec2;
        
    }

}