objects/CMPL123__Device__c.object
<CustomObject>
    <description>Device</description>
    <label>Device</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMPL123CME__MDR__c.object
<CustomObject>
    <fields>
        <fullName>CMPL123CME__Common_Device_Name__c</fullName>
        <description>Common Device Name</description>
        <label>Common Device Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Describe_Event__c</fullName>
        <description>Describe Event</description>
        <label>Describe Event</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Procode__c</fullName>
        <description>Procode</description>
        <inlineHelpText>Procode</inlineHelpText>
        <label>Procode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Type_of_Reportable_Event__c</fullName>
        <label>Type of Reportable Event</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Death</fullName>
                </value>
                <value>
                    <fullName>Serious Injury</fullName>
                </value>
                <value>
                    <fullName>Malfunction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MDR</label>
    <nameField>
        <displayFormat>MDR-{00000}</displayFormat>
        <label>SL No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MDR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CMPLCMPL123CMEMDRTriggerTest.cls
@isTest
 public   class CMPLCMPL123CMEMDRTriggerTest{
	static testMethod void CMPL123CMEMDRTriggerTestmethod(){
        
        CMPL123__Device__c testDeviceRec = new CMPL123__Device__c();
        insert testDeviceRec;
		CMPL123CME__MDR__c testobject = new CMPL123CME__MDR__c ( CMPL123CME__Common_Device_Name__c = testDeviceRec.Id,
                                                                CMPL123CME__Describe_Event__c = 'test', CMPL123CME__Procode__c = '123',
                                                               CMPL123CME__Type_of_Reportable_Event__c = 'test');
		insert testobject; 
		delete testobject; 
		undelete testobject; 
		update testobject; 
		System.assertEquals('1','1');
	}
}