objects/CMPL123CME__Complaint__c.object
<CustomObject>
    <label>Complaint</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Ticket No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Complaint_Creation_Batch_Time__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Completion_Time__c</fullName>
        <label>Batch Completion Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Email_Recipient__c</fullName>
        <label>Email Recipients</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Time_Interval__c</fullName>
        <label>Time Interval</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Complaint Creation Batch Time</label>
</CustomObject>

objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Type__c</fullName>
        <label>Error Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Case_Id__c</fullName>
        <label>External Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_ID__c</fullName>
        <label>Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Error Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Appointment__c.object
<CustomObject>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Service Appointment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Work_Order__c.object
<CustomObject>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateAllChildSchedulableBatchTest.cls
/**
*  --------------------------------------------------------------------------------------------------------------------------------------
* @Who   : Copyright (c) 2017 - 2019  Sparta Systems, Inc.
* @What  : CreateAllChildSchedulableBatchTest
* @Why   : 
* @When  : 24-JAN-2019
  
*  --------------------------------------------------------------------------------------------------------------------------------------
*  Modification Log:  
*  --------------------------------------------------------------------------------------------------------------------------------------
*   Developer                Date             Description 
*  --------------------------------------------------------------------------------------------------------------------------------------
*                        24-JAN-2019         Created.
*  --------------------------------------------------------------------------------------------------------------------------------------
**/


@isTest
public class CreateAllChildSchedulableBatchTest{

/**
* @Method       : createComplaintForCaseBatchTestMethod 
* @Invoke       : 
* @Description  : Method to test the fucntionality of CreateComplaintForCaseBatch batch class
* @Return       : N/A
* @Params       : 
**/ 
    
    public static testMethod void createComplaintForCaseBatchTestMethod(){
        
        Case cs = BMX_TestDataFactory.getCaseRecord();
        insert cs;
        Integer count = 1;
        Complaint_Creation_Batch_Time__c setting = new Complaint_Creation_Batch_Time__c();
        DateTime now = System.now();
        setting.Batch_Completion_Time__c = now;
        insert setting;
        String caseQuery = 'SELECT Id FROM Case LIMIT 1';
        
        //CreateComplaintForCaseBatch bc = new CreateComplaintForCaseBatch(caseQuery,count);
        //Database.executeBatch(bc, count); 
        
        CreateAllChildSchedulableBatch ch = new CreateAllChildSchedulableBatch();
        ch.execute(null);
    }
    
/**
* @Method       : createCaseCommentForComplaintBatchTestMethod 
* @Invoke       : 
* @Description  : Method to test the fucntionality of CreateCaseCommentForComplaintBatch batch class
* @Return       : N/A
* @Params       : 
**/ 
    
    public static testMethod void createCaseCommentForComplaintBatchTestMethod(){
        
        Case cs = BMX_TestDataFactory.getCaseRecord();
        insert cs;
        DateTime now = System.now();
        CreateCaseCommentForComplaintBatch createCaseComment = new CreateCaseCommentForComplaintBatch(true, now);
        database.executebatch(createCaseComment); 
    }
    
/**
* @Method       : createWorkOrdrForComplaintBatchTestMethod 
* @Invoke       : 
* @Description  : Method to test the fucntionality of CreateWorkOrderForComplaintBatch batch class
* @Return       : N/A
* @Params       : 
**/ 
    
    public static testMethod void createWorkOrdrForComplaintBatchTestMethod(){
        
        Case cs = BMX_TestDataFactory.getCaseRecord();
        insert cs;
        DateTime now = System.now();
        CreateWorkOrderForComplaintBatch createWorkOrdr = new CreateWorkOrderForComplaintBatch(true, now);
        database.executebatch(createWorkOrdr); 
    }
    
/**
* @Method       : createProdConsumedForWorkOrdrBatchTestMethod 
* @Invoke       : 
* @Description  : Method to test the fucntionality of CreateProductConsumedForWorkOrderBatch batch class
* @Return       : N/A
* @Params       : 
**/
    
    public static testMethod void createProdConsumedForWorkOrdrBatchTestMethod(){
        
        Case cs = BMX_TestDataFactory.getCaseRecord();
        insert cs;
        DateTime now = System.now();
        CreateProductConsumedForWorkOrderBatch createProdConsumed = new CreateProductConsumedForWorkOrderBatch(true, now);
        database.executebatch(createProdConsumed); 
    }
    
/**
* @Method       : createServiceAppointForWorkOrdrBatchTestMethod 
* @Invoke       : 
* @Description  : Method to test the fucntionality of CreateServiceAppointmentForWorkOrdrBatch batch class
* @Return       : N/A
* @Params       : 
**/
    
    public static testMethod void createServiceAppointForWorkOrdrBatchTestMethod(){
        
        Case cs = BMX_TestDataFactory.getCaseRecord();
        insert cs;
        
        Complaint_Creation_Batch_Time__c cst = new Complaint_Creation_Batch_Time__c();
        cst.Time_Interval__c = 30;
        insert cst;
        DateTime now = System.now();
        CreateServiceAppointmentForWorkOrdrBatch createServiceAppoint = new CreateServiceAppointmentForWorkOrdrBatch(true, now);
        database.executebatch(createServiceAppoint); 
    }
    
/**
* @Method       : reprocessErrorLogsBatchTestMethod 
* @Invoke       : 
* @Description  : Method to test the fucntionality of ReprocessErrorLogsBatch batch class
* @Return       : N/A
* @Params       : 
**/
    
    public static testMethod void reprocessErrorLogsBatchTestMethod(){

        Error_Log__c errlog = new Error_Log__c(External_Case_Id__c = '5007E000006OyrBQAS', Class_Name__c = 'TestABCClass',
                                              Error_Message__c = 'Foreign key external ID: 0wo6e000000k9hfwac not found for field ExternalId__c in entity Work_Order__c',
                                              Error_Type__c = 'INVALID_FIELDBatch DML Exception', Object_Name__c = 'Service_Appointment__c', Record_ID__c = 'a0P2q000000GjVn');
        insert errlog;
        
        Complaint_Creation_Batch_Time__c cst = new Complaint_Creation_Batch_Time__c();
        cst.Email_Recipient__c = 'abc@gmail.com,pqr@gmail.com';
        insert cst;
        ReprocessErrorLogsBatch_Schedule ch = new ReprocessErrorLogsBatch_Schedule();
        ch.execute(null); 
    }
    
/**
* @Method       : processReopenCloseCmplntFrCaseBatchTestMethod 
* @Invoke       : 
* @Description  : Method to test the fucntionality of ProcessReopenCloseComplaintForCaseBatch batch class
* @Return       : N/A
* @Params       : 
**/
    
    public static testMethod void processReopenCloseCmplntFrCaseBatchTestMethod(){
        
        CMPL123CME__Complaint__c cmplnt = new CMPL123CME__Complaint__c();
        insert cmplnt;
        
        List<CMPL123CME__Complaint__c> cmplntList = new List<CMPL123CME__Complaint__c>();
        cmplntList.add(cmplnt);
        DateTime now = System.now();
        ProcessReopenCloseComplaintForCaseBatch bc = new ProcessReopenCloseComplaintForCaseBatch(cmplntList,cmplntList,cmplntList, now);
        database.executebatch(bc);  
    } 
}