objects/CMPL123CME__EU_MIR__c.object
<CustomObject>
    <description>European Manufacturer Incident Report</description>
    <fields>
        <fullName>CMPL123CME__Explain_If_Investigation_Code_Missing__c</fullName>
        <description>If you think the incident is unique and a suitable IMDRF Investigation code is missing, briefly explain.</description>
        <inlineHelpText>If you think the incident is unique and a suitable IMDRF Investigation code is missing, briefly explain.</inlineHelpText>
        <label>Explain if Investigation Code missing</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Manufacturer_s_Evaluation__c</fullName>
        <description>A report of your analysis of the device involved in this event. If no analysis or investigation of the device could be carried out, for example if the device was not returned, then indicate the most probable root cause analysis. Please be clear whether you are describing the root cause or most probable root cause.
In many cases, evaluation of the actual device is not feasible. Instead the investigation may focus on "surrogate devices", i.e. devices belong to the same batch or lot as the device, to another lot/batch. Testing of model variants may also be indicated in specific cases. Please describe the devices investigated &amp; if applicable, tested-- Other investigative means than testing may include interviews with the user/operator of the device, control of production records etc. Your investigations and conclusions should be explained and their credibility and plausibility justified.
If you refer to an existing CAPA please provide the reference or identification number of that CAPA.</description>
        <inlineHelpText>A report of your analysis of the device involved in this event. If no analysis or investigation of the device could be carried out, for example if the device was not returned, then indicate the most probable root cause analysis.</inlineHelpText>
        <label>Manufacturer Evaluation Final Report</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMPL123_WF_Status__c</fullName>
        <label>Workflow Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>EU MIR</label>
    <nameField>
        <displayFormat>EU-MIR-{000000}</displayFormat>
        <label>EU MIR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EU MIR</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CMPL123CME__Investigation__c.object
<CustomObject>
    <description>INVESTIGATION AND ROOT CAUSE INFORMATION</description>
    <fields>
        <fullName>BMX_Investigation_Answer__c</fullName>
        <label>Investigation Answer</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMPL123_WF_Status__c</fullName>
        <label>Workflow Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EU_MIR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EU MIR</label>
        <referenceTo>CMPL123CME__EU_MIR__c</referenceTo>
        <relationshipLabel>Investigations/Evaluations</relationshipLabel>
        <relationshipName>Investigations_Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Justification_for_Annex_B__c</fullName>
        <inlineHelpText>This field is mandatory if you have not select the most detailed level for Type/Method</inlineHelpText>
        <label>Justification for Annex B</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Justification_for_Annex_C__c</fullName>
        <inlineHelpText>This field is mandatory if you have not select the most detailed level for Findings/Results</inlineHelpText>
        <label>Justification for Annex C</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Justification_for_Annex_D__c</fullName>
        <inlineHelpText>This field is mandatory if you have not select the most detailed level for Root Cause/Conclusion</inlineHelpText>
        <label>Justification for Annex D</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Investigation</label>
        <referenceTo>CMPL123CME__Investigation__c</referenceTo>
        <relationshipLabel>Referenced Investigations/Evaluations</relationshipLabel>
        <relationshipName>Investigations_Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Investigation/Evaluation</label>
    <nameField>
        <label>Investigation/Evaluation Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investigations/Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/INV_EUMIRUpdate_TriggerHandler.cls
public class INV_EUMIRUpdate_TriggerHandler{

@future
public static void updateINVEUMIR(List<Id> invIdList)
{

    map<Id,CMPL123CME__Investigation__c> MIRInvestmap= new map<Id,CMPL123CME__Investigation__c>();

    List<CMPL123CME__Investigation__c> Chinvrecords = [SELECT id,CMPL123_WF_Status__c,EU_MIR__c,Master_Investigation__c,BMX_Investigation_Answer__c,Justification_for_Annex_B__c,Justification_for_Annex_C__c,Justification_for_Annex_D__c FROM CMPL123CME__Investigation__c WHERE Master_Investigation__c IN : invIdList ];
    system.debug('MasterInvChildrecords...MSR:::'+Chinvrecords);
    for(CMPL123CME__Investigation__c inv :Chinvrecords)   
    {
      if(inv.CMPL123_WF_Status__c  == 'Closed - Done')
      {           
            
            if(String.isNotBlank(inv.Justification_for_Annex_B__c) || String.isNotBlank(inv.Justification_for_Annex_C__c) || String.isNotBlank(inv.Justification_for_Annex_D__c))
            {            
                MIRInvestmap.put(inv.EU_MIR__c,inv);
            }
            
        }
    }
        List<CMPL123CME__EU_MIR__c> EMIRlistupdt= new List<CMPL123CME__EU_MIR__c>();
        system.debug('EMIRlistupdt...MSR:::'+EMIRlistupdt);
        system.debug('MIRInvestmap@@@MIRID@@InvestValues::'+MIRInvestmap);
        if(!MIRInvestmap.isEmpty())
        {
            List<CMPL123CME__EU_MIR__c> EMIRlist=[select id,CMPL123CME__Explain_If_Investigation_Code_Missing__c,CMPL123CME__Manufacturer_s_Evaluation__c from CMPL123CME__EU_MIR__c where Id IN:MIRInvestmap.keyset()];
            for(CMPL123CME__EU_MIR__c emr: EMIRlist)
            {
                CMPL123CME__EU_MIR__c mr= new CMPL123CME__EU_MIR__c();
                mr.Id=emr.Id;
               // mr.CMPL123CME__Explain_If_Investigation_Code_Missing__c= MIRInvestmap.get(emr.Id).Justification_for_Annex_B__c+MIRInvestmap.get(emr.Id).Justification_for_Annex_C__c+MIRInvestmap.get(emr.Id).Justification_for_Annex_D__c;
                mr.CMPL123CME__Explain_If_Investigation_Code_Missing__c= ((MIRInvestmap.get(emr.Id).Justification_for_Annex_B__c==null)?'':MIRInvestmap.get(emr.Id).Justification_for_Annex_B__c)+' '+'/'+' '+((MIRInvestmap.get(emr.Id).Justification_for_Annex_C__c==null)?'':MIRInvestmap.get(emr.Id).Justification_for_Annex_C__c)+' '+'/'+' '+((MIRInvestmap.get(emr.Id).Justification_for_Annex_D__c==null)?'':MIRInvestmap.get(emr.Id).Justification_for_Annex_D__c);
                mr.CMPL123CME__Manufacturer_s_Evaluation__c=MIRInvestmap.get(emr.Id).BMX_Investigation_Answer__c;
                EMIRlistupdt.add(mr);
            }
        }
        if(!EMIRlistupdt.isEmpty() && EMIRlistupdt.size()>0)
        {
            update EMIRlistupdt;
        }
    
   }

 
}