objects/CMPL123CME__Complaint__c.object
<CustomObject>
    <label>Complaint</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Ticket No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMPL123CME__EU_MIR__c.object
<CustomObject>
    <description>European Manufacturer Incident Report</description>
    <fields>
        <fullName>CMPL123CME__Complaint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Complaint.</description>
        <inlineHelpText>Related Complaint.</inlineHelpText>
        <label>Complaint</label>
        <referenceTo>CMPL123CME__Complaint__c</referenceTo>
        <relationshipLabel>EU MIR</relationshipLabel>
        <relationshipName>EU_MIR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMPL123_WF_Status__c</fullName>
        <label>Workflow Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Investigation_Evaluation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation/Evaluation</label>
        <referenceTo>CMPL123CME__Investigation__c</referenceTo>
        <relationshipLabel>EU MIR</relationshipLabel>
        <relationshipName>EU_MIR</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EU MIR</label>
    <nameField>
        <displayFormat>EU-MIR-{000000}</displayFormat>
        <label>EU MIR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EU MIR</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CMPL123CME__Investigation__c.object
<CustomObject>
    <description>INVESTIGATION AND ROOT CAUSE INFORMATION</description>
    <fields>
        <fullName>CMPL123CME__Complaint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Complaint</label>
        <referenceTo>CMPL123CME__Complaint__c</referenceTo>
        <relationshipName>Investigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMPL123_WF_Status__c</fullName>
        <label>Workflow Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EU_MIR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EU MIR</label>
        <referenceTo>CMPL123CME__EU_MIR__c</referenceTo>
        <relationshipLabel>Investigations/Evaluations</relationshipLabel>
        <relationshipName>Investigations_Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Investigation/Evaluation</label>
    <nameField>
        <label>Investigation/Evaluation Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investigations/Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InvestigationTriggerHandler.cls
public class InvestigationTriggerHandler {
    
    Public static void InvestiToEumirupdate(list<CMPL123CME__Investigation__c> myinvestlist){

        Map<Id, Id> investcmpltmap = new Map<Id, Id>();
        List<CMPL123CME__EU_MIR__c> updtEMRlist= new List<CMPL123CME__EU_MIR__c>();
        Map<Id, CMPL123CME__EU_MIR__c> complainIdToInvstIdMap = new Map<Id, CMPL123CME__EU_MIR__c>();
        
        for(CMPL123CME__Investigation__c inv:myinvestlist){
           if(inv.CMPL123CME__Complaint__c !=null && inv.EU_MIR__c==null){
              investcmpltmap.put(inv.CMPL123CME__Complaint__c,inv.Id);
           }
        } 
    if(!investcmpltmap.isEmpty())
    {        
    for(CMPL123CME__EU_MIR__c Mir :[SELECT Id,CMPL123CME__Complaint__c,CMPL123_WF_Status__c,Investigation_Evaluation__c from CMPL123CME__EU_MIR__c WHERE (CMPL123_WF_Status__c like '%Opened%') AND Investigation_Evaluation__c=null AND CMPL123CME__Complaint__c In:investcmpltmap.keyset()]){
            complainIdToInvstIdMap.put(Mir.CMPL123CME__Complaint__c,Mir);
            CMPL123CME__EU_MIR__c em= new CMPL123CME__EU_MIR__c();
            em.Id=Mir.Id;
            em.Investigation_Evaluation__c=investcmpltmap.get(mir.CMPL123CME__Complaint__c);
            updtEMRlist.add(em);  
        }
    }
        
    if(!updtEMRlist.isempty()){
        update updtEMRlist;
    }

    if(!complainIdToInvstIdMap.isEmpty()){
    
        List<CMPL123CME__Investigation__c> updtinv= new List<CMPL123CME__Investigation__c>();
        List<CMPL123CME__Investigation__c> invstList=[SELECT Id,EU_MIR__c,CMPL123CME__Complaint__c from CMPL123CME__Investigation__c where id IN:investcmpltmap.values()];
        
        for(CMPL123CME__Investigation__c inv:invstList)
        {
            CMPL123CME__Investigation__c i= new CMPL123CME__Investigation__c();
            i.Id=inv.Id;
            i.EU_MIR__c=complainIdToInvstIdMap.get(inv.CMPL123CME__Complaint__c).Id;
            updtinv.add(i);
 
        }
    
        if(!updtinv.isEmpty())
        {
            update updtinv;
        }
        
    }
    
 }

}