objects/CMPL123CME__Complaint__c.object
<CustomObject>
    <label>Complaint</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Ticket No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMPL123CME__Investigation__c.object
<CustomObject>
    <description>INVESTIGATION AND ROOT CAUSE INFORMATION</description>
    <fields>
        <fullName>BMX_Containment_Correction_Action__c</fullName>
        <label>Containment/Correction Action</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BMX_Date_Product_Received__c</fullName>
        <label>Date Product Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BMX_Evidence_of_Trend__c</fullName>
        <label>Evidence of Trend</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BMX_Expert_Investigator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expert Investigator</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Investigations/Evaluations</relationshipLabel>
        <relationshipName>Investigations_Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BMX_Impact_Analysis__c</fullName>
        <label>Impact Analysis</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BMX_Investigation_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Investigations_EvaluationsFF0F</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BMX_Investigation_Details__c</fullName>
        <label>Investigation Details</label>
        <length>25000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BMX_Is_there_a_trend__c</fullName>
        <label>Is there a trend?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BMX_Product_Returned__c</fullName>
        <label>Product Returned?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Return Requested</fullName>
                </value>
                <value>
                    <fullName>Product Return Not Requested</fullName>
                </value>
                <value>
                    <fullName>Product Return Not Received</fullName>
                </value>
                <value>
                    <fullName>Product Return Received</fullName>
                </value>
                <value>
                    <fullName>Product Return Cancelled</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BMX_Return_Comments__c</fullName>
        <label>Return Comments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Complaint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Complaint</label>
        <referenceTo>CMPL123CME__Complaint__c</referenceTo>
        <relationshipName>Investigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMPL123_WF_Status__c</fullName>
        <label>Workflow Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Investigation/Evaluation</label>
    <nameField>
        <label>Investigation/Evaluation Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investigations/Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Investchildupdate_Test.cls
@isTest
private class Investchildupdate_Test {
       
  public static testmethod void myTest() 
  {
      // User initialization
        Profile p = [select id from profile where name='Standard User'];

        User u = new User(alias = 'utest', email='utest@email.com',
            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
            localesidkey='en_US', profileid = p.Id, country='United States',
            timezonesidkey='America/Los_Angeles', username='utest123@email.com');
    insert u;
      
    CMPL123CME__Complaint__c cmplnt = new CMPL123CME__Complaint__c();
    insert cmplnt;
      
    CMPL123CME__Investigation__c Invest=new CMPL123CME__Investigation__c();
        Invest.Name='TWD TestInvestigation';
		Invest.BMX_Investigation_Approver__c=u.id;        
        Invest.CMPL123CME__Complaint__c=cmplnt.Id;
        invest.BMX_Product_Returned__c='Product Return Requested';
      	invest.BMX_Date_Product_Received__c=system.today()+15;
        invest.BMX_Return_Comments__c='Test';
        invest.BMX_Is_there_a_trend__c='Yes';
      	invest.CMPL123_WF_Status__c='Opened';
      	invest.BMX_Evidence_of_Trend__c='testing';
        invest.BMX_Containment_Correction_Action__c='Testing';
        invest.BMX_Investigation_Details__c='my Test';
      	invest.BMX_Impact_Analysis__c='my Test';
        invest.BMX_Expert_Investigator__c='testing';
      
        Insert Invest;
  }
    

}