objects/CMPL123QMS__Change_Control__c.object
<CustomObject>
    <label>Change Control</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Change Control Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Control</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SAP_Product_Information__c.object
<CustomObject>
    <fields>
        <fullName>CE_Approved__c</fullName>
        <label>CE Approved</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Control__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Change Control</label>
        <referenceTo>CMPL123QMS__Change_Control__c</referenceTo>
        <relationshipLabel>SAP Product Information</relationshipLabel>
        <relationshipName>SAP_Product_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commercialization_Coverage__c</fullName>
        <label>Commercialization Coverage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Trade_Identification_Number__c</fullName>
        <label>Global Trade Identification Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Manufacturer__c</fullName>
        <label>Legal Manufacturer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Make_or_Buy__c</fullName>
        <label>Make or Buy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Item_Description__c</fullName>
        <label>Product Item Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Item_Number__c</fullName>
        <label>Product Item Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Range__c</fullName>
        <label>Product Range</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Responsible__c</fullName>
        <label>Site Responsible</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_Type__c</fullName>
        <label>Trade Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SAP Product Information</label>
    <nameField>
        <displayFormat>SAPPI-{000000000}</displayFormat>
        <label>SAP Product Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAP Product Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SapProductInformationController.cls
/**
 * @File Name          : SapProductInformationController.cls
 * @Description        : 
 * @Author             : Jon Astemborski
 * @Group              : 
 * @Last Modified By   : Jon Astemborski
 * @Last Modified On   : 2/11/2020, 10:51:43 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    2/10/2020   Jon Astemborski     Initial Version
**/
public without sharing class SapProductInformationController {
    public SapProductInformationController() {

    }

    public static void handleUpdateAfterProductImpacted(Map<Id,CMPL123QMS__Change_Control__c> newMap, Map<Id,CMPL123QMS__Change_Control__c> oldMap){
        List<SAP_Product_Information__c> productInformationList = new List<SAP_Product_Information__c>();
        List<CMPL123QMS__Change_Control__c> ccList = new List<CMPL123QMS__Change_Control__c>();
        for ( CMPL123QMS__Change_Control__c cc : newMap.values()){
            if ( oldMap.get(cc.id).Product_Impacted__c != null && oldMap.get(cc.id).Product_Impacted__c != newMap.get(cc.id).Product_Impacted__c) {
                String prodImpacted = cc.Product_Impacted__c != null ? cc.Product_Impacted__c.toUpperCase() : '';
                if ( String.isBlank(prodImpacted) || prodImpacted.contains('NO') ||  prodImpacted.toUpperCase().equals('YES – SINGLE ITEM IMPACTED') ||
                   		prodImpacted.equals('YES – MULTIPLE ITEMS IMPACTED')) {
                    productInformationList = [SELECT Id FROM SAP_Product_Information__c WHERE Change_Control__c =: cc.id];
                    System.debug('list: ' + productInformationList);
                    cc.Product_Item_Number__c = '';
                    cc.Product_Item_Description__c = '';
                    cc.Product_Range__c = '';
                    cc.Global_Trade_Identification_Number__c = '';
                    cc.CE_Approved__c = '';
                    cc.Product_Type__c = '';
                    cc.Make_or_Buy__c = '';
                    cc.Trade_Type__c = '';
                    cc.Legal_Manufacturer__c = '';
                    cc.Site_Responsible__c = '';
                    cc.Commercialization_Coverage__c = '';
                    cc.Origin__c = '';
                }
            }
            if (! productInformationList.isEmpty() ){
                delete productInformationList;
                system.debug('delete');
            }
        }
        
    }
}