objects/CMPL123CME__Complaint__c.object
<CustomObject>
    <fields>
        <fullName>Assessment_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Assessment Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Complaints_Assigned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__CMPL123_WF_Action__c</fullName>
        <label>Workflow Action</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Impact__c</fullName>
        <description>Impact</description>
        <label>Impact</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Initiator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Initiator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Complaints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Short_Description__c</fullName>
        <description>Short Description</description>
        <label>Short Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Complaints_Supervisor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation_Status__c</fullName>
        <label>Investigation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Investigation Completed</fullName>
                </value>
                <value>
                    <fullName>Investigation Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Ticket No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMPL123CME__Questionnaire__c.object
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Questionnaire No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Complaint</fullName>
        <active>true</active>
        <label>Complaint</label>
    </recordTypes>
</CustomObject>

classes/AssessmentHandler_Test.cls
@isTest public class AssessmentHandler_Test {
    @IsTest public static void testAssessmentHandler1() {
        // User initialization
        Profile p = [select id from profile where name='Standard User'];
        
        User testUser1 = new User(alias = 'utest', email='utest@email.com',
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                          localesidkey='en_US', profileid = p.Id, country='United States',
                          timezonesidkey='America/Los_Angeles', username='testUser1BMX@email.com');
        insert testUser1;
        
        //complaint obj:
        CMPL123CME__Complaint__c complaintObj;
        complaintObj = new CMPL123CME__Complaint__c();
        complaintObj.CMPL123CME__Assigned_To__c = testUser1.Id;
        complaintObj.CMPL123CME__Short_Description__c ='UnitTest';
        complaintObj.CMPL123CME__Initiator__c = testUser1.id;
        complaintObj.CMPL123CME__Supervisor__c = testUser1.Id;
        complaintObj.CMPL123CME__Impact__c = 'Low';
        insert complaintObj;

        List<CMPL123CME__Questionnaire__c> lstQuestObj = new List<CMPL123CME__Questionnaire__c> ();
        
        CMPL123CME__Questionnaire__c qustObj;
        qustObj = new CMPL123CME__Questionnaire__c();
        qustObj.CMPL123CME__Complaint__c = complaintObj.Id;
        lstQuestObj.add(qustObj);
        
        qustObj = new CMPL123CME__Questionnaire__c();
        qustObj.CMPL123CME__Complaint__c = complaintObj.Id;
        lstQuestObj.add(qustObj);
        
        insert lstQuestObj;
        
        AssessmentHandler.preventAssessmentDelete(lstQuestObj);
        delete lstQuestObj;
        
    }
     @IsTest public static void testAssessmentHandler2() {
        // User initialization
        Profile p = [select id from profile where name='Standard User'];
        
        User u1 = new User(alias = 'utest1', email='utest1@email.com',
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                          localesidkey='en_US', profileid = p.Id, country='United States',
                          timezonesidkey='America/Los_Angeles', username='utest1@email.com');
        insert u1;
        
        //complaint obj:
        CMPL123CME__Complaint__c complaintObj;
        complaintObj = new CMPL123CME__Complaint__c();
        complaintObj.CMPL123CME__Assigned_To__c = u1.Id;
        complaintObj.CMPL123CME__Short_Description__c ='UnitTest';
        complaintObj.CMPL123CME__Initiator__c = u1.id;
        complaintObj.CMPL123CME__Supervisor__c = u1.Id;
        complaintObj.CMPL123CME__Impact__c = 'Low';
         complaintObj.CMPL123CME__CMPL123_WF_Action__c = 'Close - Complaint';
         
        insert complaintObj;
        complaintObj.Assessment_Completed__c = true;
         complaintObj.Investigation_Status__c= 'Investigation Completed';
         update complaintObj;
         
        List<CMPL123CME__Questionnaire__c> lstQuestObj = new List<CMPL123CME__Questionnaire__c>();
        
        CMPL123CME__Questionnaire__c qustObj;
        for(Integer i =0;i<2 ; i++)
        {
        qustObj = new CMPL123CME__Questionnaire__c();
        qustObj.CMPL123CME__Complaint__c = complaintObj.Id;
        lstQuestObj.add(qustObj);
        }
            
         
        insert lstQuestObj;
        delete lstQuestObj;
        
    }
}