objects/CMPL123CME__Complaint__c.object
<CustomObject>
    <fields>
        <fullName>CMPL123CME__Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Complaints_Assigned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Impact__c</fullName>
        <description>Impact</description>
        <label>Impact</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Initiator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Initiator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Complaints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Short_Description__c</fullName>
        <description>Short Description</description>
        <label>Short Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Complaints_Supervisor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer / Distributor</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Field Outsourced Companies</fullName>
                </value>
                <value>
                    <fullName>Regulatory Authorities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Ticket No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Inquiry__c.object
<CustomObject>
    <fields>
        <fullName>Inquiry_Type__c</fullName>
        <label>Inquiry Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Request for Information</fullName>
                </value>
                <value>
                    <fullName>Product or Packaging</fullName>
                </value>
                <value>
                    <fullName>Patient Event</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Manufactured_by_Company__c</fullName>
        <label>Manufactured by Company?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Patient_Affected__c</fullName>
        <label>Patient Affected?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_or_Packaging_Issue__c</fullName>
        <label>Product or Packaging Issue?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Support</fullName>
                </value>
                <value>
                    <fullName>Mail</fullName>
                </value>
                <value>
                    <fullName>email</fullName>
                </value>
                <value>
                    <fullName>Telephone</fullName>
                </value>
                <value>
                    <fullName>Web</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Inquiry</label>
    <nameField>
        <displayFormat>INQ-{0000}</displayFormat>
        <label>Inquiry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestPrevent_Complaint_Delete_Trigger.cls
/**
#############################################################################
#  File Name     : Complaint_Test_Class
#  Author        : Sparta Systems 
#  Description: public class which is used to handle all the custom functioanlity on Complaint object. 


#############################################################################
*/
@IsTest Public Class TestPrevent_Complaint_Delete_Trigger{
    
    @IsTest Public static Void Prevent_Complaint_Delete_Trigger(){
        
        // User initialization
        Profile p = [select id from profile where name='Standard User'];
        
        User u = new User(alias = 'utest', email='utest@email.com',
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                          localesidkey='en_US', profileid = p.Id, country='United States',
                          timezonesidkey='America/Los_Angeles', username='utestCmpl@email.com');
        insert u;
        
        //Instantiate a new Inquiry object with all required parameter in the page
        Inquiry__c InqObj = new Inquiry__c();
        InqObj.Source__c = 'Email';
        InqObj.Subject__c = 'UnitTest';
        InqObj.Inquiry_Type__c = 'Patient Event';
        InqObj.Manufactured_by_Company__c = 'Yes';
        InqObj.Product_or_Packaging_Issue__c='Yes';
        InqObj.Patient_Affected__c='Yes';
        insert InqObj;
        
        List<CMPL123CME__Complaint__c> complaintObj = new List<CMPL123CME__Complaint__c>();
        
        CMPL123CME__Complaint__c complaintObj1 ;
        
        complaintObj1  = new CMPL123CME__Complaint__c() ;
        complaintObj1 = new CMPL123CME__Complaint__c();
        complaintObj1.CMPL123CME__Assigned_To__c = u.Id;
        complaintObj1.CMPL123CME__Short_Description__c ='UnitTest';
        complaintObj1.CMPL123CME__Initiator__c = u.id;
        complaintObj1.CMPL123CME__Supervisor__c = u.Id;
        complaintObj1.CMPL123CME__Impact__c = 'High';        
        complaintObj.add(complaintObj1);
        
        try{
            
            insert complaintObj; 
        }
        catch(Exception ex)  
        {
            system.debug('exception'+ex);
        }    
        delete complaintObj;   
        delete InqObj;
    }
    
}