objects/CMPL123CME__Complaint__c.object
<CustomObject>
    <fields>
        <fullName>BMX_Assessment_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Assessment Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BMX_Batch_Expiration_Date__c</fullName>
        <label>Batch Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BMX_Batch_Number_Reagent__c</fullName>
        <label>Batch Number (Reagent)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BMX_Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>BMX_Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BMX_Contact_Phone__c</fullName>
        <label>Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>BMX_Customer_Contact_Date__c</fullName>
        <label>Customer Contact Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BMX_PRE__c</fullName>
        <label>PRE</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BMX_Product_Code__c</fullName>
        <inlineHelpText>Correspond to Product Code for Product, whatever it’s an instrument or a reagent</inlineHelpText>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BMX_Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BMX_Reference__c</fullName>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BMX_Serial_Number_Asset__c</fullName>
        <label>Serial Number (Asset)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visitor_Address_Name__c</fullName>
        <label>Visitor Address Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visitor_City__c</fullName>
        <label>Visitor City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visitor_Country__c</fullName>
        <label>Visitor Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visitor_Postal_Code__c</fullName>
        <label>Visitor PostalCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visitor_Street__c</fullName>
        <label>Visitor Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Ticket No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BMX_CreateGlobalAsmntFrCMPBatchTest.cls
/* 
* @why  : BMX_CreateGlobalAssessmentBatchTest test class for the BMX_CreateGlobalAssessmentFrCMPLBatch class
* @when : CreatedDate :  may-28-2019        ModifiedDate : 
* @what : Class to Handle Different scenarios for BMX_CreateGlobalAssessmentFrCMPLBatch.
*/

@isTest
public class BMX_CreateGlobalAsmntFrCMPBatchTest {
    
/**    
* @description:   creating the required test data.
* @param:         void
* @return:        void
**/ 
    
    @testSetup static void setup(){
        
        // Create the Complaint Record
        CMPL123CME__Complaint__c complaint = (CMPL123CME__Complaint__c)BMX_TestDataFactory.createSObject(new CMPL123CME__Complaint__c(
         BMX_Reference__c = 'test',BMX_Product_Code__c = 'test',BMX_Product_Name__c = 'test',BMX_Contact_Name__c = 'test',
         BMX_Batch_Expiration_Date__c = Date.newInstance(2018, 12, 8), Visitor_Street__c = 'test',Visitor_City__c = 'test',
         BMX_Contact_Email__c = 'a@test.com',BMX_Contact_Phone__c = '1234567',Visitor_Postal_Code__c = '560066', 
         Visitor_Country__c = 'India',BMX_Batch_Number_Reagent__c ='2345',BMX_Customer_Contact_Date__c = Date.newInstance(2018, 10, 8),
         Visitor_Address_Name__c = 'test',BMX_Serial_Number_Asset__c = '123', BMX_PRE__c = 'Yes', BMX_Assessment_Created__c = False
        ),true);
        
        // Create the Complaint Record
        CMPL123CME__Complaint__c complaint1 = (CMPL123CME__Complaint__c)BMX_TestDataFactory.createSObject(new CMPL123CME__Complaint__c(
         BMX_Reference__c = 'test1',BMX_Product_Code__c = 'test11',BMX_Product_Name__c = 'test1',BMX_Contact_Name__c = 'test1',
         BMX_Batch_Expiration_Date__c = Date.newInstance(2018, 12, 8), Visitor_Street__c = 'test',Visitor_City__c = 'test',
         BMX_Contact_Email__c = 'ab@test.com',BMX_Contact_Phone__c = '1234567',Visitor_Postal_Code__c = '560066', 
         Visitor_Country__c = 'India',BMX_Batch_Number_Reagent__c ='2345',BMX_Customer_Contact_Date__c = Date.newInstance(2018, 10, 8),
         Visitor_Address_Name__c = 'test',BMX_Serial_Number_Asset__c = '123', BMX_PRE__c = 'Yes', BMX_Assessment_Created__c = False
        ),true);
    
     }
     
 /**    
* @description:   Test method for Auto creation of Global Assessment for Complaint.
* @param:         void
* @return:        void
**/ 
    
     public static testMethod void autoCreateGATestMethod(){
     
         List<CMPL123CME__Complaint__c> cmplList = [Select Id,BMX_PRE__c, Visitor_Country__c,BMX_Assessment_Created__c  FROM CMPL123CME__Complaint__c Where Visitor_Country__c = 'India' Limit 2];
         Test.startTest();
         BMX_CreateGlobalAssessmentFrCMPLBatch crGA = new BMX_CreateGlobalAssessmentFrCMPLBatch(cmplList);
         DataBase.executeBatch(crGA);
         Test.stopTest();
     }
}