objects/CMPL123CME__Investigation__c.object
<CustomObject>
    <description>INVESTIGATION AND ROOT CAUSE INFORMATION</description>
    <label>Investigation/Evaluation</label>
    <nameField>
        <label>Investigation/Evaluation Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investigations/Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMPL123CME__Investigation_Items__c.object
<CustomObject>
    <fields>
        <fullName>CMPL123CME__Investigation__c</fullName>
        <label>Parent Investigation</label>
        <referenceTo>CMPL123CME__Investigation__c</referenceTo>
        <relationshipLabel>Investigation Items</relationshipLabel>
        <relationshipName>Investigation_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation Items</label>
    <nameField>
        <displayFormat>II-{00000}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigation Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CMPL123CMEInv_ItemsTriggerTest.cls
@isTest
 public   class CMPL123CMEInv_ItemsTriggerTest{
	static testMethod void CMPL123CMEInvestigation_ItemsTriggerTestmethod(){
        
        CMPL123CME__Investigation__c investRec = new CMPL123CME__Investigation__c();
        insert investRec;
		CMPL123CME__Investigation_Items__c testobject = new CMPL123CME__Investigation_Items__c (CMPL123CME__Investigation__c = investRec.Id );
		insert testobject; 
		delete testobject; 
		undelete testobject; 
		update testobject; 
		System.assertEquals('1','1');
	}
}