objects/CMPL123QMS__Change_Control__c.object
<CustomObject>
    <label>Change Control</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Change Control Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Control</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SAP_Product_Information__c.object
<CustomObject>
    <fields>
        <fullName>Change_Control__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Change Control</label>
        <referenceTo>CMPL123QMS__Change_Control__c</referenceTo>
        <relationshipLabel>SAP Product Information</relationshipLabel>
        <relationshipName>SAP_Product_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Item_Description__c</fullName>
        <label>Product Item Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Item_Number__c</fullName>
        <label>Product Item Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SAP Product Information</label>
    <nameField>
        <displayFormat>SAPPI-{000000000}</displayFormat>
        <label>SAP Product Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAP Product Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SapRelatedProductsHandler.cls
/**
 * @File Name          : SapRelatedProductsHandler.cls
 * @Description        : 
 * @Author             : Jon Astemborski
 * @Group              : 
 * @Last Modified By   : Jon Astemborski
 * @Last Modified On   : 2/11/2020, 9:44:31 AM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    2/10/2020   Jon Astemborski     Initial Version
**/
public without sharing class SapRelatedProductsHandler {
    @AuraEnabled
    public static List<SAP_Product_Information__c> productInformationList {get; set;} 

    @AuraEnabled
    public static String recordId {get;set;}
    
    public SapRelatedProductsHandler() {
        productInformationList = new List<SAP_Product_Information__c>();
    }

    @AuraEnabled
    public static void removeRecords(List<SAP_Product_Information__c> sapRecords){
        try{
       delete sapRecords;
        }
        catch (Exception e)
        {
            System.debug(e);
        }
    }

    @AuraEnabled
    public static List<SAP_Product_Information__c> retrieveSapProductInformation(String recordId){
       return [SELECT Id, Product_Item_Number__c, Product_Item_Description__c FROM SAP_Product_Information__c WHERE change_control__c =: recordId];
    }

    @AuraEnabled
    public static boolean areMultipleProductsImpacted(String recordId){
        CMPL123QMS__Change_Control__c cc = [SELECT Id, Product_Impacted__c FROM CMPL123QMS__Change_Control__c  WHERE id =: recordId limit 1];
        if (cc.Product_Impacted__c  != null ) {
            return cc.Product_Impacted__c.toUpperCase().equals('YES – MULTIPLE ITEMS IMPACTED') ? true : false;
        }
        return false;
    }
}