objects/CMPL123CME__Complaint__c.object
<CustomObject>
    <label>Complaint</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Ticket No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMPL123CME__EU_MIR__c.object
<CustomObject>
    <description>European Manufacturer Incident Report</description>
    <fields>
        <fullName>CMPL123CME__Complaint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Complaint.</description>
        <inlineHelpText>Related Complaint.</inlineHelpText>
        <label>Complaint</label>
        <referenceTo>CMPL123CME__Complaint__c</referenceTo>
        <relationshipLabel>EU MIR</relationshipLabel>
        <relationshipName>EU_MIR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMPL123CME__Type_Of_Report__c</fullName>
        <description>Initial - Your first report on an incident. May be initiated under Vigilance system or from User Incident Report notified to you by relevant CA. 
*Follow-up - Provide additional/interim information during your investigation. Can submit more than 1 follow-up. 
*Combined initial &amp; final - Details of initial &amp; final report within the initial timeframe for reporting. 
*Final (Reportable)- Formal statement of the outcome of your investigation, including any actions proposed or taken.It is recognized that a further ‘Final’ report may be necessary in circumstances where additional information only becomes available at a later stage.Applicable for both vigilance reports submitted in compliance with MDD/IVDD (30 days) and for MDR/IVDR (15 days)
Final (Non-reportable)- Event reported in initial report does not fulfill reporting criteria.By selecting this the only mandatory field is 4.2a and no other fields in Section 4
*This option is not available once you have submitted an initial report.</description>
        <inlineHelpText>Initial - First report on a particular incident.
Follow-up - Additional information. 
Initial &amp; Final - Details of initial &amp; final. 
Final Reportable - Statement of investigation outcome.
Final Non-reportable - Event in initial is not reportable.</inlineHelpText>
        <label>Type of report</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                </value>
                <value>
                    <fullName>Follow up</fullName>
                </value>
                <value>
                    <fullName>Combined initial and final</fullName>
                </value>
                <value>
                    <fullName>Final (Reportable incident)</fullName>
                </value>
                <value>
                    <fullName>Final (Non-reportable incident)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CMPL123_WF_Status__c</fullName>
        <label>Workflow Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Investigation_Evaluation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation/Evaluation</label>
        <referenceTo>CMPL123CME__Investigation__c</referenceTo>
        <relationshipLabel>EU MIR</relationshipLabel>
        <relationshipName>EU_MIR</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EU MIR</label>
    <nameField>
        <displayFormat>EU-MIR-{000000}</displayFormat>
        <label>EU MIR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EU MIR</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CMPL123CME__Investigation__c.object
<CustomObject>
    <description>INVESTIGATION AND ROOT CAUSE INFORMATION</description>
    <fields>
        <fullName>CMPL123CME__Complaint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Complaint</label>
        <referenceTo>CMPL123CME__Complaint__c</referenceTo>
        <relationshipName>Investigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMPL123_WF_Status__c</fullName>
        <label>Workflow Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EU_MIR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EU MIR</label>
        <referenceTo>CMPL123CME__EU_MIR__c</referenceTo>
        <relationshipLabel>Investigations/Evaluations</relationshipLabel>
        <relationshipName>Investigations_Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Investigation/Evaluation</label>
    <nameField>
        <label>Investigation/Evaluation Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investigations/Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EU_MIR_InvestigationHandler_Invocable.cls
public class EU_MIR_InvestigationHandler_Invocable {
    
    @InvocableMethod
    public static void populateInvist_Updatein(List<EU_mirWrapper> EMIRSetId)
    {
    
        try 
        {
            system.debug('MSR::EMIRSetId...'+EMIRSetId);
            List<CMPL123CME__EU_MIR__c> mirlist=[Select id,CMPL123CME__Complaint__c,CMPL123CME__Type_Of_Report__c from CMPL123CME__EU_MIR__c where id=:EMIRSetId[0].Eumirids];
            List<CMPL123CME__Investigation__c> invstList = new List<CMPL123CME__Investigation__c>();
            List<CMPL123CME__EU_MIR__c> eumirList = new List<CMPL123CME__EU_MIR__c>();
            if(checkRecursiveonEMIR.isFirstTime)
            {
                checkRecursiveonEMIR.isFirstTime = false;
                Map<Id, Id> cmptmap = new Map<Id, Id>();             
                for(CMPL123CME__EU_MIR__c mir:mirlist)
                {
                     if(mir.CMPL123CME__Complaint__c !=null && (mir.CMPL123CME__Type_Of_Report__c == 'Initial'|| mir.CMPL123CME__Type_Of_Report__c=='Follow up') ){     
                        cmptmap.put(mir.CMPL123CME__Complaint__c,mir.Id);
                     }
                
                }
                
                system.debug('MSR::cmptmap...'+cmptmap);
                Map<Id, Id> complainIdToInvstIdMap = new Map<Id, Id>(); 
                if(!cmptmap.isEmpty())
                {
                
                    for(CMPL123CME__Investigation__c inv:[SELECT Id,CMPL123CME__Complaint__c,EU_MIR__c,CMPL123_WF_Status__c FROM CMPL123CME__Investigation__c WHERE (NOT CMPL123_WF_Status__c like '%Closed%') AND CMPL123CME__Complaint__c IN:cmptmap.keyset()])
                    {
                        complainIdToInvstIdMap.put(inv.CMPL123CME__Complaint__c, inv.Id);
                        
                    }
                }
                
                system.debug('MSR::complainIdToInvstIdMap...'+complainIdToInvstIdMap);
                if(!complainIdToInvstIdMap.isEmpty())
                {
                    
                    List<CMPL123CME__EU_MIR__c> eumirnewlist=[Select id,CMPL123CME__Complaint__c,CMPL123CME__Type_Of_Report__c from CMPL123CME__EU_MIR__c where id IN:cmptmap.values()];
                    for(CMPL123CME__EU_MIR__c mir:eumirnewlist){
                        if(mir.CMPL123CME__Complaint__c !=null && (mir.CMPL123CME__Type_Of_Report__c == 'Initial'|| mir.CMPL123CME__Type_Of_Report__c=='Follow up')){
                        
                            invstList.add(new CMPL123CME__Investigation__c(Id = complainIdToInvstIdMap.get(mir.CMPL123CME__Complaint__c), EU_MIR__c = mir.Id));
                            
                            eumirList.add(new CMPL123CME__EU_MIR__c(Id = mir.Id, Investigation_Evaluation__c = complainIdToInvstIdMap.get(mir.CMPL123CME__Complaint__c)));
                        }
                    }
                }
            }
            system.debug('MSR::eumirList::'+eumirList);
                if(!eumirList.isEmpty())
                   update eumirList;
                if(!invstList.isEmpty())
                    update invstList;
            
            
        } catch(DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
    
    }
    
    Public class EU_mirWrapper
    {
        @InvocableVariable
        public Id Eumirids;
    }
    
    
 }