objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Type__c</fullName>
        <label>Error Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Case_Id__c</fullName>
        <label>External Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_ID__c</fullName>
        <label>Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Error Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ReprocessErrorLogsBatch_Schedule.cls
/**
*  --------------------------------------------------------------------------------------------------------------------------------------
* @Who   : Copyright (c) 2017 - 2019  Sparta Systems, Inc.
* @What  : ReprocessErrorLogsBatch_Schedule 
* @Why   : Batch class to execute ReprocessErrorLogsBatch batch class
* @When  : 23-APR-2019
  
*  --------------------------------------------------------------------------------------------------------------------------------------
*  Modification Log:  
*  --------------------------------------------------------------------------------------------------------------------------------------
*   Developer                Date             Description 
*  --------------------------------------------------------------------------------------------------------------------------------------
*                        23-APR-2019        Created.
*  --------------------------------------------------------------------------------------------------------------------------------------
**/

public class ReprocessErrorLogsBatch_Schedule implements Schedulable,Database.AllowsCallouts{
    
    public void execute(SchedulableContext sc){
        //Datetime timestamp = System.now().addHours(-24);
		
		// Querying Error log object and passing the data to the ReprocessErrorLogsBatch batch class to execute 
        String query = 'SELECT Id,Name,External_Case_Id__c, Class_Name__c, Error_Message__c, Error_Type__c, Object_Name__c, Record_ID__c FROM Error_Log__c WHERE LastModifiedDate >=: timeStamp';
        ReprocessErrorLogsBatch bc = new ReprocessErrorLogsBatch(query);
        Database.executeBatch(bc, 200) ;        
    }
}